package lt.views;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JComponent;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.KeyStroke;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableColumnModel;
import lt.dao.DaoCliente;
import lt.dao.DaoTipoPlan;
import lt.dao.DaoVehiculo;
import lt.interfaces.InterfaceBuscadorVehiculo;
import lt.interfaces.InterfaceCliente;
import lt.interfaces.InterfacePoliza;
import lt.models.Cliente;
import lt.models.TipoPlan;
import lt.models.Vehiculo;
import lt.tablas.ModeloTablaCliente;
import lt.tablas.ModeloTablaVehiculosClienteSeleccionado;


/**
 *
 * @author brother
 */
public class buscadorClienteVehiculo extends javax.swing.JDialog {

    /**
     * Creates new form FormularioClasificacionProductos
     */
    private Cliente cliente;
    private DaoCliente daoCliente;
    private ModeloTablaCliente mtCliente;
    private ModeloTablaVehiculosClienteSeleccionado mtVehiculo;
    private List<Cliente> clientes;
    private InterfaceCliente interfaceCliente;
    private InterfacePoliza interfacePoliza;
    private InterfaceBuscadorVehiculo interfaceVehiculo;
    private DaoVehiculo daoVehiculo;
    private List<Vehiculo> vehiculos;
    private DaoTipoPlan daoPlan;
    private List<TipoPlan> planes;
    private Vehiculo vehiculo;

    public void setInterfaceCliente(InterfaceCliente interfaceCliente) {
        this.interfaceCliente = interfaceCliente;
    }

    public void setInterfacePoliza(InterfacePoliza interfacePoliza) {
        this.interfacePoliza = interfacePoliza;
    }

    public buscadorClienteVehiculo() {
        initComponents();
        setLocationRelativeTo(this);
        TableColumnModel columnModel = tabla.getColumnModel();
        columnModel.getColumn(1).setPreferredWidth(400);

        recuperarPorFiltro();

        //Metodos abreviados
        formateoTabla();
        buscarAbreviado(this);
        seleccionarAbreviado(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        mtCliente = new ModeloTablaCliente();
        tabla = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        tfDescripcion = new javax.swing.JTextField();
        btnBusqueda = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnSeleccionar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Buscador de Clientes");
        setBackground(new java.awt.Color(237, 244, 246));
        setModal(true);

        jScrollPane1.getViewport().setBackground(new java.awt.Color(255, 255, 255));

        tabla.setModel(mtCliente);
        tabla.setSelectionBackground(new java.awt.Color(92, 132, 228));

        tabla.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel1.setText("Descripción");

        tfDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfDescripcionKeyPressed(evt);
            }
        });

        btnBusqueda.setBackground(new java.awt.Color(45, 118, 232));
        btnBusqueda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lt/images/search_20px_1.png"))); // NOI18N
        btnBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBusquedaActionPerformed(evt);
            }
        });

        jPanel1.setLayout(new java.awt.GridLayout(1, 0, 3, 3));

        btnSeleccionar.setBackground(new java.awt.Color(45, 118, 232));
        btnSeleccionar.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnSeleccionar.setForeground(new java.awt.Color(255, 255, 255));
        btnSeleccionar.setText("Seleccionar");
        btnSeleccionar.setEnabled(false);
        btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(307, 307, 307)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBusqueda)
                        .addGap(92, 92, 92)
                        .addComponent(btnSeleccionar)))
                .addGap(24, 24, 24))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tfDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnSeleccionar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusquedaActionPerformed
        recuperarPorFiltro();
    }//GEN-LAST:event_btnBusquedaActionPerformed

    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarActionPerformed
                  seleccionarCliente(tabla.getSelectedRow());
  
    }//GEN-LAST:event_btnSeleccionarActionPerformed

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
             if (evt.getClickCount() == 2) {
            seleccionarCliente(tabla.getSelectedRow());
        }
    }//GEN-LAST:event_tablaMouseClicked

    private void tfDescripcionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfDescripcionKeyPressed

    }//GEN-LAST:event_tfDescripcionKeyPressed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JButton btnBusqueda;
    public static javax.swing.JButton btnSeleccionar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField tfDescripcion;
    // End of variables declaration//GEN-END:variables

    private void recuperarPorFiltro() {
        daoCliente = new DaoCliente();
        clientes = daoCliente.recuperarPorFiltro(tfDescripcion.getText());
        mtCliente.setLista(clientes);

    }

    private void seleccionarCliente(int index) {
        if (index < 0) {
            return;
        }
        cliente = clientes.get(index);
        interfaceCliente.setCliente(cliente);
           dispose();
    }

    

    //Metodo abreviado para buscar un registro
    public static void buscarAbreviado(final JDialog dialog) {
        ActionListener listener = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                btnBusqueda.doClick();

            }
        };
        dialog.getRootPane().registerKeyboardAction(listener, KeyStroke.getKeyStroke(KeyEvent.VK_F3, 0), JComponent.WHEN_IN_FOCUSED_WINDOW);
    }

    //Metodo abreviado para Limpiar el formulario
    public static void seleccionarAbreviado(final JDialog dialog) {
        ActionListener listener = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                btnSeleccionar.doClick();

            }
        };
        dialog.getRootPane().registerKeyboardAction(listener, KeyStroke.getKeyStroke(KeyEvent.VK_F9, 0), JComponent.WHEN_IN_FOCUSED_WINDOW);
    }
      private void formateoTabla() {
        TableColumnModel columnModel = tabla.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(200);
        columnModel.getColumn(1).setPreferredWidth(140);
        columnModel.getColumn(2).setPreferredWidth(140);
        columnModel.getColumn(3).setPreferredWidth(130);
        tabla.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tabla.doLayout();

        //alineamiento de celdas
        DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
        tcr.setHorizontalAlignment(SwingConstants.RIGHT);

        // jTable1.getColumnModel().getColumn(3).setCellRenderer(tcr);
    }
    //Fin de los metodos abreviados para la ventana
}
