/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lt.views;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableColumnModel;
import lt.dao.DaoVehiculo;
import lt.interfaces.InterfaceCliente;
import lt.models.Cliente;
import lt.models.Vehiculo;
import lt.tablas.ModeloTablaVehiculos;
import lt.util.ConnectionHelper;
import lt.util.Utilidad;



/**
 *
 * @author brother
 */
public class CarView extends javax.swing.JDialog implements InterfaceCliente {

    /**
     * Creates new form VehiculoView
     */
    private Vehiculo vehiculo;
    private DaoVehiculo daoVehiculo;
    private ModeloTablaVehiculos mtvehiculo;
    private List<Vehiculo> vehiculoslist;
    private String accion;
    private Cliente cliente;
    private int img = 1;

    public CarView() {
        super();
        initComponents();
        setLocationRelativeTo(this);
        recuperarTodo();
        formateoTabla();
        estadoInicial(true);
        Utilidad.soloLetras(txMarca);
        Utilidad.soloLetras(txColor);
        
        Utilidad.soloNumeros(txAnho);
      
        //mayusculas
        txMarca.setDocument(new Utilidad());
        txPlaca.setDocument(new Utilidad());
        txModelo.setDocument(new Utilidad());
        txNumeroMotor.setDocument(new Utilidad());
        txNroSerie.setDocument(new Utilidad());
        txCilindrada.setDocument(new Utilidad());
        txPotencia.setDocument(new Utilidad());
        txColor.setDocument(new Utilidad());
        txBusqueda.setDocument(new Utilidad());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        head = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        lblClientePropietario = new javax.swing.JLabel();
        lblCedula = new javax.swing.JLabel();
        txBusqueda = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        body = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        txPlaca = new javax.swing.JTextField();
        txMarca = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txAnho = new javax.swing.JTextField();
        txModelo = new javax.swing.JTextField();
        txNumeroMotor = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txNroSerie = new javax.swing.JTextField();
        txCilindrada = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txColor = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        chkAire = new javax.swing.JCheckBox();
        txPotencia = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cbCombustible = new javax.swing.JComboBox<>();
        cbDireccion = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        btnAgregarPropietario = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        mtvehiculo = new ModeloTablaVehiculos();
        jTable1 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnImg = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro y Modificación de Vehículos");
        setModal(true);
        setResizable(false);

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        head.setBackground(new java.awt.Color(45, 118, 232));
        head.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lt/images/car.png"))); // NOI18N
        head.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Código:");
        head.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 50, -1));

        lblCodigo.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lblCodigo.setForeground(new java.awt.Color(255, 255, 255));
        head.add(lblCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, 20));

        lblClientePropietario.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblClientePropietario.setForeground(new java.awt.Color(255, 255, 255));
        lblClientePropietario.setText("No asignado");
        head.add(lblClientePropietario, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        lblCedula.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        lblCedula.setForeground(new java.awt.Color(255, 255, 255));
        lblCedula.setText("No asignado");
        head.add(lblCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, -1, -1));

        txBusqueda.setBackground(new java.awt.Color(45, 118, 232));
        txBusqueda.setForeground(new java.awt.Color(255, 255, 255));
        txBusqueda.setBorder(null);
        txBusqueda.setCaretColor(new java.awt.Color(255, 255, 255));
        txBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txBusquedaActionPerformed(evt);
            }
        });
        txBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txBusquedaKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txBusquedaKeyPressed(evt);
            }
        });
        head.add(txBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 160, 30));

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cliente:");
        head.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        jLabel16.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("CINº:");
        head.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, -1));
        head.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 170, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lt/images/search_20px_1.png"))); // NOI18N
        head.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, -1, -1));

        jPanel6.add(head, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 120));

        body.setBackground(new java.awt.Color(237, 244, 246));

        jPanel1.setBackground(new java.awt.Color(237, 244, 246));

        txPlaca.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txPlaca.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, null));
        txPlaca.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txPlaca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txPlacaKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txPlacaKeyPressed(evt);
            }
        });

        txMarca.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txMarca.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, null));
        txMarca.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txMarca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txMarcaKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txMarcaKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel3.setText("Placa:");

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel4.setText("Marca:");

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel5.setText("Año Fab.:");

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel6.setText("Modelo:");

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel7.setText("Motor N°:");

        txAnho.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txAnho.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, null));
        txAnho.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txAnho.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txAnhoKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txAnhoKeyPressed(evt);
            }
        });

        txModelo.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txModelo.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, null));
        txModelo.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txModelo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txModeloKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txModeloKeyPressed(evt);
            }
        });

        txNumeroMotor.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txNumeroMotor.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, null));
        txNumeroMotor.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txNumeroMotor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txNumeroMotorKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txNumeroMotorKeyPressed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel10.setText("N° de Serie:");
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        txNroSerie.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txNroSerie.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, null));
        txNroSerie.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txNroSerie.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txNroSerieKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txNroSerieKeyPressed(evt);
            }
        });

        txCilindrada.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txCilindrada.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, null));
        txCilindrada.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txCilindrada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txCilindradaKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txCilindradaKeyPressed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel13.setText("Cilindrada:");
        jLabel13.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        txColor.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txColor.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, null));
        txColor.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txColor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txColorKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txColorKeyPressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel9.setText("Color:");
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        chkAire.setBackground(new java.awt.Color(237, 244, 246));
        chkAire.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        chkAire.setText("Aire Acondicionado");
        chkAire.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                chkAireKeyPressed(evt);
            }
        });

        txPotencia.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txPotencia.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, null));
        txPotencia.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txPotencia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txPotenciaKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txPotenciaKeyPressed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel12.setText("Potencia:");
        jLabel12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel14.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel14.setText("Propietario:");

        jLabel11.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel11.setText("Combustible:");

        cbCombustible.setBackground(new java.awt.Color(237, 244, 246));
        cbCombustible.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        cbCombustible.setRenderer(new DefaultListCellRenderer() {
            @Override
            public void paint(Graphics g) {
                setForeground(new java.awt.Color(51, 51, 51));
                super.paint(g);
            }
        });
        cbCombustible.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Diesel", "Gasolina" }));
        cbCombustible.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbCombustibleKeyPressed(evt);
            }
        });

        cbDireccion.setBackground(new java.awt.Color(237, 244, 246));
        cbDireccion.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        cbDireccion.setRenderer(new DefaultListCellRenderer() {
            @Override
            public void paint(Graphics g) {
                setForeground(new java.awt.Color(51, 51, 51));
                super.paint(g);
            }
        });
        cbDireccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hidraulica","Electrica" }));
        cbDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbDireccionKeyPressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel8.setText("Dirección:");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        btnAgregarPropietario.setBackground(new java.awt.Color(45, 118, 232));
        btnAgregarPropietario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lt/images/search_20px_1.png"))); // NOI18N
        btnAgregarPropietario.setFocusPainted(false);
        btnAgregarPropietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPropietarioActionPerformed(evt);
            }
        });
        btnAgregarPropietario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnAgregarPropietarioKeyPressed(evt);
            }
        });

        jScrollPane2.getViewport().setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jScrollPane2KeyReleased(evt);
            }
        });

        jTable1.setModel(mtvehiculo);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jPanel5.setLayout(new java.awt.GridLayout(1, 3, 6, 6));

        btnGuardar.setBackground(new java.awt.Color(45, 118, 232));
        btnGuardar.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lt/images/guardar35.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/lt/images/guardardisa.png"))); // NOI18N
        btnGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGuardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        btnGuardar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnGuardarKeyPressed(evt);
            }
        });
        jPanel5.add(btnGuardar);

        btnNuevo.setBackground(new java.awt.Color(45, 118, 232));
        btnNuevo.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnNuevo.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lt/images/nuevo35.png"))); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/lt/images/nuevodisa.png"))); // NOI18N
        btnNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jPanel5.add(btnNuevo);

        btnModificar.setBackground(new java.awt.Color(45, 118, 232));
        btnModificar.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(255, 255, 255));
        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lt/images/actualizar35.png"))); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/lt/images/actualizardisa.png"))); // NOI18N
        btnModificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnModificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel5.add(btnModificar);

        btnCancelar.setBackground(new java.awt.Color(45, 118, 232));
        btnCancelar.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lt/images/cancelar35.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/lt/images/cancelardisa.png"))); // NOI18N
        btnCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel5.add(btnCancelar);

        btnEliminar.setBackground(new java.awt.Color(45, 118, 232));
        btnEliminar.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lt/images/eliminar35.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/lt/images/eliminardisa.png"))); // NOI18N
        btnEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel5.add(btnEliminar);

        btnSalir.setBackground(new java.awt.Color(45, 118, 232));
        btnSalir.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lt/images/salir35.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/lt/images/salirdisa.png"))); // NOI18N
        btnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel5.add(btnSalir);

        btnImg.setBackground(new java.awt.Color(255, 255, 255));
        btnImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lt/images/icons8-Eye-35.png"))); // NOI18N
        btnImg.setEnabled(false);
        btnImg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImgActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel4)
                    .add(jLabel6)
                    .add(jLabel5)
                    .add(jLabel3)
                    .add(jLabel10)
                    .add(jLabel7)
                    .add(jLabel13))
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(txCilindrada, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 138, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(txNroSerie, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 138, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(txNumeroMotor, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 130, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(txPlaca, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 80, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(txAnho, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(15, 15, 15)
                        .add(txModelo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 150, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(18, 18, 18)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(120, 120, 120)
                                .add(cbCombustible, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 89, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jLabel11, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 130, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jLabel8)
                                .add(61, 61, 61)
                                .add(cbDireccion, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 107, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .add(29, 29, 29)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel9)
                            .add(jLabel12))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(txPotencia, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 77, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(txColor, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 103, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1Layout.createSequentialGroup()
                            .add(chkAire)
                            .add(182, 182, 182)
                            .add(btnImg, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 56, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 478, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(0, 0, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jPanel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 765, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(240, 240, 240))
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(96, 96, 96)
                        .add(txMarca, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 150, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(12, 12, 12)
                        .add(jLabel14)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(btnAgregarPropietario, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 52, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(btnAgregarPropietario, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(8, 8, 8)
                                .add(jLabel14)))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(txMarca, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(10, 10, 10)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(txModelo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel6))
                        .add(9, 9, 9)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(txAnho, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel5))
                        .add(9, 9, 9)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(txPlaca, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel3))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(txNumeroMotor, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel7)
                            .add(jLabel11)
                            .add(cbCombustible, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel9)
                            .add(txColor, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(txNroSerie, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel10)
                            .add(jLabel8)
                            .add(cbDireccion, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel12)
                            .add(txPotencia, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(12, 12, 12)
                        .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 182, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jLabel13)
                        .add(txCilindrada, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(chkAire, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(btnImg, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 45, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 28, Short.MAX_VALUE)
                .add(jPanel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 70, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout bodyLayout = new org.jdesktop.layout.GroupLayout(body);
        body.setLayout(bodyLayout);
        bodyLayout.setHorizontalGroup(
            bodyLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 800, Short.MAX_VALUE)
        );
        bodyLayout.setVerticalGroup(
            bodyLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel6.add(body, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 800, 470));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jPanel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 799, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jPanel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        if (validar()) {
            guardar();
        }

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        nuevo();

    }//GEN-LAST:event_btnNuevoActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        seleccionarObjeto(jTable1.getSelectedRow());
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnAgregarPropietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPropietarioActionPerformed
        // TODO add your handling code here:
        buscadorCliente busCliente = new buscadorCliente();
        busCliente.setInterfaceCliente(this);
        buscadorCliente.btnSeleccionar.setEnabled(true);
        busCliente.setVisible(true);
    }//GEN-LAST:event_btnAgregarPropietarioActionPerformed

    private void txBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txBusquedaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txBusquedaActionPerformed

    private void txAnhoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txAnhoKeyTyped
        Utilidad.limitarCaracteresTextField(evt, txAnho, 4);
    }//GEN-LAST:event_txAnhoKeyTyped

    private void txModeloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txModeloKeyTyped
        // TODO add your handling code here:
        Utilidad.limitarCaracteresTextField(evt, txModelo, 30);
    }//GEN-LAST:event_txModeloKeyTyped

    private void txPlacaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txPlacaKeyTyped
        Utilidad.limitarCaracteresTextField(evt, txPlaca, 6);
    }//GEN-LAST:event_txPlacaKeyTyped

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        eliminar();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        cancelar();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void txBusquedaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txBusquedaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            buscar();
        }
    }//GEN-LAST:event_txBusquedaKeyPressed

    private void txMarcaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txMarcaKeyPressed
        Utilidad.moverConEnter(evt, txModelo);
    }//GEN-LAST:event_txMarcaKeyPressed

    private void cbCombustibleKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbCombustibleKeyPressed
        Utilidad.moverConEnter(evt, txColor);
    }//GEN-LAST:event_cbCombustibleKeyPressed

    private void txModeloKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txModeloKeyPressed
        Utilidad.moverConEnter(evt, txAnho);
    }//GEN-LAST:event_txModeloKeyPressed

    private void txNroSerieKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txNroSerieKeyPressed
        Utilidad.moverConEnter(evt, cbDireccion);
    }//GEN-LAST:event_txNroSerieKeyPressed

    private void cbDireccionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbDireccionKeyPressed
        Utilidad.moverConEnter(evt, txPotencia);
    }//GEN-LAST:event_cbDireccionKeyPressed

    private void txAnhoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txAnhoKeyPressed
        Utilidad.moverConEnter(evt, txPlaca);
    }//GEN-LAST:event_txAnhoKeyPressed

    private void txCilindradaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txCilindradaKeyPressed
        Utilidad.moverConEnter(evt, chkAire);
    }//GEN-LAST:event_txCilindradaKeyPressed

    private void txPlacaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txPlacaKeyPressed
        Utilidad.moverConEnter(evt, txNumeroMotor);
    }//GEN-LAST:event_txPlacaKeyPressed

    private void txPotenciaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txPotenciaKeyPressed
        Utilidad.moverConEnter(evt, txCilindrada);
    }//GEN-LAST:event_txPotenciaKeyPressed

    private void chkAireKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_chkAireKeyPressed
        Utilidad.moverConEnter(evt, btnGuardar);
    }//GEN-LAST:event_chkAireKeyPressed

    private void txNumeroMotorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txNumeroMotorKeyPressed
        Utilidad.moverConEnter(evt, cbCombustible);
    }//GEN-LAST:event_txNumeroMotorKeyPressed

    private void txColorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txColorKeyPressed
        Utilidad.moverConEnter(evt, txNroSerie);
    }//GEN-LAST:event_txColorKeyPressed

    private void btnAgregarPropietarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnAgregarPropietarioKeyPressed
        Utilidad.hacerClicConEnter(evt, btnAgregarPropietario);
    }//GEN-LAST:event_btnAgregarPropietarioKeyPressed

    private void txBusquedaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txBusquedaKeyTyped
        Utilidad.limitarCaracteresTextField(evt, txBusqueda, 6);
    }//GEN-LAST:event_txBusquedaKeyTyped

    private void jScrollPane2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jScrollPane2KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane2KeyReleased

    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased
        // TODO add your handling code here:
        seleccionarObjeto(jTable1.getSelectedRow());
    }//GEN-LAST:event_jTable1KeyReleased

    private void txMarcaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txMarcaKeyTyped
        Utilidad.limitarCaracteresTextField(evt, txMarca, 20);
    }//GEN-LAST:event_txMarcaKeyTyped

    private void txNumeroMotorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txNumeroMotorKeyTyped
        Utilidad.limitarCaracteresTextField(evt, txNumeroMotor, 20);
    }//GEN-LAST:event_txNumeroMotorKeyTyped

    private void txNroSerieKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txNroSerieKeyTyped
        Utilidad.limitarCaracteresTextField(evt, txNroSerie, 17);
    }//GEN-LAST:event_txNroSerieKeyTyped

    private void txCilindradaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txCilindradaKeyTyped
        Utilidad.limitarCaracteresTextField(evt, txCilindrada, 30);
    }//GEN-LAST:event_txCilindradaKeyTyped

    private void txPotenciaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txPotenciaKeyTyped
        Utilidad.limitarCaracteresTextField(evt, txPotencia, 30);
    }//GEN-LAST:event_txPotenciaKeyTyped

    private void txColorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txColorKeyTyped
        Utilidad.limitarCaracteresTextField(evt, txColor, 20);
    }//GEN-LAST:event_txColorKeyTyped

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        modificar();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImgActionPerformed
        if (txPlaca.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "El campo de matricula no fue rellenado, verifique");
            txPlaca.requestFocus();
        }else{
            ImgAdd imagen = new ImgAdd();
            imagen.setVisible(true);
        }
    }//GEN-LAST:event_btnImgActionPerformed

    private void btnGuardarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnGuardarKeyPressed
         if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (validar()) {
            guardar();
        }
        }
    }//GEN-LAST:event_btnGuardarKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        ConnectionHelper.setUp();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CarView dialog = new CarView();
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel body;
    private javax.swing.JButton btnAgregarPropietario;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    public static javax.swing.JButton btnImg;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cbCombustible;
    private javax.swing.JComboBox<String> cbDireccion;
    private javax.swing.JCheckBox chkAire;
    private javax.swing.JPanel head;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblClientePropietario;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JTextField txAnho;
    private javax.swing.JTextField txBusqueda;
    private javax.swing.JTextField txCilindrada;
    private javax.swing.JTextField txColor;
    private javax.swing.JTextField txMarca;
    private javax.swing.JTextField txModelo;
    private javax.swing.JTextField txNroSerie;
    private javax.swing.JTextField txNumeroMotor;
    public static javax.swing.JTextField txPlaca;
    private javax.swing.JTextField txPotencia;
    // End of variables declaration//GEN-END:variables

    //Methods Declarations:
    private void estadoInicial(Boolean estado) {
        //textFields    
        //campos de vehiculo
        txBusqueda.setEnabled(estado);
        txAnho.setEnabled(!estado);
        txMarca.setEnabled(!estado);
        txModelo.setEnabled(!estado);
        txNroSerie.setEnabled(!estado);
        txCilindrada.setEnabled(!estado);
        txColor.setEnabled(!estado);
        btnImg.setEnabled(!estado);
        txPotencia.setEnabled(!estado);
        txPlaca.setEnabled(!estado);
        txNumeroMotor.setEnabled(!estado);

        //comboBox
        cbCombustible.setEnabled(!estado);
        cbDireccion.setEnabled(!estado);
        //checkBox
        chkAire.setEnabled(!estado);
        //botones
        btnNuevo.setEnabled(estado);
        //btnBuscar.setEnabled(estado);
        btnEliminar.setEnabled(!estado);
        btnGuardar.setEnabled(!estado);
        btnCancelar.setEnabled(!estado);
        btnModificar.setEnabled(!estado);
        btnAgregarPropietario.setEnabled(!estado);
        //tabla de cliente
        jTable1.clearSelection();
        jTable1.setEnabled(estado);
        //focus
        txBusqueda.requestFocus();
    }

    private void vaciarCampos() {
        //textFields
        //campos de cliente
        lblClientePropietario.setText("");
        lblCedula.setText("");
        //campos de vehiculo
        lblCodigo.setText("");
        txAnho.setText("");
        txMarca.setText("");
        txModelo.setText("");
        txNroSerie.setText("");
        txCilindrada.setText("");
        txColor.setText("");
        txPotencia.setText("");
        txPlaca.setText("");
        txNumeroMotor.setText("");
        lblClientePropietario.setText("");

    }

    private void guardar() {
         if (accion.equals("NUEVO")) {
            vehiculo = new Vehiculo();
        }
       
        vehiculo.setMarca(txMarca.getText());
        vehiculo.setModelo(txModelo.getText());
        vehiculo.setAnho(Integer.parseInt(txAnho.getText()));
        vehiculo.setPlaca(txPlaca.getText());
        vehiculo.setNumeroMotor(txNumeroMotor.getText());
        vehiculo.setNumeroSerie(txNroSerie.getText());
        vehiculo.setCilindrada(txCilindrada.getText());
        vehiculo.setPotenciaMaxima(txPotencia.getText());
        vehiculo.setColor(txColor.getText());
        vehiculo.setCombustible(String.valueOf(cbCombustible.getSelectedItem()));
        vehiculo.setDireccion(String.valueOf(cbDireccion.getSelectedItem()));
        vehiculo.setAireAcondicionado(chkAire.isSelected());
        vehiculo.setCliente(cliente);

        try {
            daoVehiculo = new DaoVehiculo();
            if (accion.equals("NUEVO")) {
                daoVehiculo.insertar(vehiculo);
            } else {
                daoVehiculo.actualizar(vehiculo);
            }
            daoVehiculo.commit();

            recuperarTodo();
            estadoInicial(true);
            //vaciarCampos();
        } catch (Exception e) {
            daoVehiculo.rollback();
               String error = "org.hibernate.exception.ConstraintViolationException: could not execute statement";
            if (e.toString().equals(error)) {
                JOptionPane.showMessageDialog(null, "Ya se ha registrado un cliente con la matrícula: "+txPlaca.getText()+"\n"+" Favor verifique");
                txPlaca.requestFocus();
            }else{
            JOptionPane.showMessageDialog(null, "Se ha producido un error en la carga de datos" );
            } ;
           
        }
    }

    private void nuevo() {
        accion = "NUEVO";
        
        estadoBotonesNuevoUpdate();
        
        
        vaciarCampos();
        setearIdNuevo();
        btnAgregarPropietario.requestFocus();
        lblClientePropietario.setText("Para iniciar la carga, asigne un cliente");
        btnGuardar.setEnabled(false);
    }
      private void estadoBotonesNuevoUpdate() {
         btnAgregarPropietario.setEnabled(true);
         
        btnNuevo.setEnabled(false);
        btnEliminar.setEnabled(false);
        btnGuardar.setEnabled(true);
        btnCancelar.setEnabled(true);
        btnModificar.setEnabled(false);
        txMarca.requestFocus();
         jTable1.clearSelection();
        jTable1.setEnabled(false);

    }

    private void setearIdNuevo() {
        daoVehiculo = new DaoVehiculo();
        Integer id = daoVehiculo.recuperarUltimoID() + 1;
        lblCodigo.setText(id + "");

    }

    private void formateoTabla() {
        TableColumnModel columnModel = jTable1.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(85);
        columnModel.getColumn(1).setPreferredWidth(70);
        columnModel.getColumn(2).setPreferredWidth(80);
        columnModel.getColumn(3).setPreferredWidth(80);
        columnModel.getColumn(4).setPreferredWidth(85);
        columnModel.getColumn(5).setPreferredWidth(75);
        jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        jTable1.doLayout();

        //alineamiento de celdas
        DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
        tcr.setHorizontalAlignment(SwingConstants.CENTER);

        // jTable1.getColumnModel().getColumn(3).setCellRenderer(tcr);
    }

    private void eliminar() {
        int index = jTable1.getSelectedRow();
        if (index < 0) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un Vehículo");
            return;
        }
        vehiculo = vehiculoslist.get(index);
        int result = JOptionPane.showConfirmDialog(null,
                "Está  seguro en eliminar el vehículo"
                + vehiculo.getMarca() + " " + "con placa n° " + vehiculo.getPlaca(),
                "Atención", JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION) {
            daoVehiculo = new DaoVehiculo();
            try {
                daoVehiculo.eliminar(vehiculo);
                daoVehiculo.commit();
                recuperarTodo();
                vaciarCampos();
            } catch (Exception e) {
                daoVehiculo.rollback();
                JOptionPane.showMessageDialog(null, "Operación no permitida, no se puede eliminar un Vehículo asegurado. \n");
            }
        }

    }

    private void seleccionarObjeto(int index) {
        if (index < 0) {

            return;
        }

        vehiculo = vehiculoslist.get(index);

        lblCodigo.setText(vehiculo.getCodigo() + "");
        txPlaca.setText(vehiculo.getPlaca());
        txMarca.setText(vehiculo.getMarca());
        txAnho.setText(vehiculo.getAnho() + "");
        txModelo.setText(vehiculo.getModelo());
        txNumeroMotor.setText(vehiculo.getNumeroMotor());
        txNroSerie.setText(vehiculo.getNumeroSerie());
        txColor.setText(vehiculo.getColor());
        txCilindrada.setText(vehiculo.getCilindrada());
        cbCombustible.setSelectedItem(vehiculo.getCombustible());
        txPotencia.setText(vehiculo.getPotenciaMaxima());
        cbDireccion.setSelectedItem(vehiculo.getDireccion());
        chkAire.setSelected(vehiculo.isAireAcondicionado());

        //setear el nombre del cliente relacionado con el vehiculo
        lblClientePropietario.setText(vehiculo.getCliente().getNombre() + " " + vehiculo.getCliente().getApellido());
        lblCedula.setText(vehiculo.getCliente().getCin() + "");
        //guardar imagen

//        lblImagen.setIcon(new javax.swing.ImageIcon("/home/brother/Documents/ImagenesSeguro/" + txPlaca.getText() + "_" + img + ".jpg"));
        botonesSeleccionarObjeto();

    }

    private boolean validar() {
        boolean validar = false;
        if (txMarca.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "El campo Marca debe ser rellenado, favor verifique");
            txMarca.requestFocus();
        } else if (txModelo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "El campo Modelo debe ser rellenado, favor verifique");
            txModelo.requestFocus();
        } else if (txAnho.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "El campo Año debe ser rellenado, favor verifique");
            txAnho.requestFocus();
        } else if (txPlaca.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "El campo Placa debe ser rellenado, favor verifique");
            txPlaca.requestFocus();
        } else if (txNumeroMotor.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "El campo Número de Motor debe ser rellenado, favor verifique");
            txNumeroMotor.requestFocus();
        } else if (txColor.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "El campo Color debe ser rellenado, favor verifique");
            txColor.requestFocus();
        } else if (txNroSerie.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "El campo Número de Serie debe ser rellenado, favor verifique");
            txNroSerie.requestFocus();
        } else if (txPotencia.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "El campo Potencia debe ser rellenado, favor verifique");
            txPotencia.requestFocus();
        } else if (txCilindrada.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "El campo Cilindrada debe ser rellenado, favor verifique");
            txCilindrada.requestFocus();
        } else if (lblClientePropietario.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "El campo Propietario debe ser rellenado, favor verifique");
            btnAgregarPropietario.requestFocus();
        } else {
            validar = true;
        }

        return validar;

    }

    private void botonesSeleccionarObjeto() {
        //botones
        btnNuevo.setEnabled(false);
        // btnBuscar.setEnabled(true);
        btnEliminar.setEnabled(true);
        btnGuardar.setEnabled(false);
        btnCancelar.setEnabled(true);
        btnModificar.setEnabled(true);
        btnImg.setEnabled(true);

    }

    private void recuperarTodo() {
        daoVehiculo = new DaoVehiculo();
        vehiculoslist = daoVehiculo.recuperarTodo();
        mtvehiculo.setLista(vehiculoslist);
    }
//ver un metodo de abm imagenes con tamanho predefinido
    //crear un if para limitar el tamanho de las imagenes

    @Override
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
        lblClientePropietario.setText(cliente.getNombre()+" "+cliente.getApellido());
        lblCedula.setText(cliente.getCin() + "");
        //txPropietario.setText(cliente.getNombre() + " " + cliente.getApellido());
        estadoInicial(false);
        btnModificar.setEnabled(false);
        btnEliminar.setEnabled(false);
        txMarca.requestFocus();
    }

    private void cancelar() {
        vaciarCampos();
        estadoInicial(true);
        txBusqueda.setText("");
    }

    private void buscar() {
        daoVehiculo = new DaoVehiculo();
        String placa = txBusqueda.getText();
        vehiculoslist = daoVehiculo.recuperarPorFiltro(placa);
        if (vehiculoslist.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Vehículo no encontrado");
            txBusqueda.setText("");
            txBusqueda.requestFocus();;
        }else{
             mtvehiculo.setLista(vehiculoslist);
        }
       
    }

    private void modificar() {
         accion = "MODIFICAR";
         estadoInicial(false);
        estadoBotonesNuevoUpdate();
         
    }
}
