/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lt.views;


import java.text.ParseException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import lt.dao.DaoCiudad;
import lt.dao.DaoCliente;
import lt.interfaces.InterfaceCliente;
import lt.models.Cliente;
import lt.models.Distritos;
import lt.util.Utilidad;



/**
 *
 * @author brother
 */
public class ClienteAlta extends javax.swing.JDialog {


    
    private Cliente cliente;
    private List<Cliente> listaCliente;
   
    private DaoCliente dao;
    InterfaceCliente interfaceCliente;
    private DaoCiudad daoDistrito;
    private ArrayList<Object> ciudades;
    private List<Distritos> distritos;
    private Distritos distrito;

    public void setInterfaceCliente(InterfaceCliente interfaceCliente) {
        this.interfaceCliente = interfaceCliente;
        
    }
    
    
   


    /**
     * Creates new form Cliente
     */
    public ClienteAlta() {
        
        initComponents();
        setLocationRelativeTo(this);
        //solo letras
        Utilidad.soloLetras(txApellido);
        Utilidad.soloNumeros(txCedula);
        
        Utilidad.soloLetras(txDireccion);
        Utilidad.soloLetras(txNombre);
        Utilidad.soloNumeros(txTelefono);
        //mayusculas        
        txApellido.setDocument(new Utilidad());
      
        txDireccion.setDocument(new Utilidad());
        txNombre.setDocument(new Utilidad());
        recuperarCiudades();
        
     
       
    }




        /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        //seaglass
//      
//        ConnectionHelper.setUp();
//  
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                ClienteAlta dialog = new ClienteAlta(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    ClienteAlta(JDialog jDialog) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txApellido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txCedula = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txTelefono = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txDireccion = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cbCiudades = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nuevo Cliente");
        setModal(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Datos del Cliente"));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(new java.awt.GridLayout(12, 1));

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel2.setText("Nombre(s):");
        jPanel1.add(jLabel2);

        txNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txNombreActionPerformed(evt);
            }
        });
        jPanel1.add(txNombre);

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel3.setText("Apellido(s):");
        jPanel1.add(jLabel3);
        jPanel1.add(txApellido);

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel4.setText("C.I.N°:");
        jPanel1.add(jLabel4);

        txCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txCedulaActionPerformed(evt);
            }
        });
        jPanel1.add(txCedula);

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel5.setText("Teléfono:");
        jPanel1.add(jLabel5);
        jPanel1.add(txTelefono);

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel6.setText("Dirección:");
        jPanel1.add(jLabel6);

        txDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txDireccionActionPerformed(evt);
            }
        });
        jPanel1.add(txDireccion);

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel7.setText("Ciudad:");
        jPanel1.add(jLabel7);

        cbCiudades.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));
        jPanel1.add(cbCiudades);

        btnGuardar.setBackground(new java.awt.Color(45, 118, 232));
        btnGuardar.setFont(new java.awt.Font("Roboto", 0, 10)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(45, 118, 232));
        btnCancelar.setFont(new java.awt.Font("Roboto", 0, 10)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancelar.setMaximumSize(new java.awt.Dimension(86, 43));
        btnCancelar.setMinimumSize(new java.awt.Dimension(86, 43));
        btnCancelar.setPreferredSize(new java.awt.Dimension(86, 43));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(45, 118, 232));
        btnSalir.setFont(new java.awt.Font("Roboto", 0, 10)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("Salir");
        btnSalir.setMaximumSize(new java.awt.Dimension(86, 43));
        btnSalir.setMinimumSize(new java.awt.Dimension(86, 43));
        btnSalir.setPreferredSize(new java.awt.Dimension(86, 43));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txCedulaActionPerformed

    private void txDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txDireccionActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        cancelar();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void txNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txNombreActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        guardar();
        
    }//GEN-LAST:event_btnGuardarActionPerformed

//METODOS

    private void guardar(){
      daoDistrito = new DaoCiudad();
        distrito = daoDistrito.recuperarDistritosPorParametro(cbCiudades.getSelectedItem().toString());
            cliente = new Cliente();
  
        cliente.setNombre(txNombre.getText());
        cliente.setApellido(txApellido.getText());
        cliente.setCin(Integer.parseInt(txCedula.getText()));
        cliente.setTelefono(txTelefono.getText());
        cliente.setDireccion(txDireccion.getText());
        cliente.setDistrito(distrito);
        
        
        dao = new DaoCliente();
    
             
        try {
            dao.insertar(cliente);
        } catch (Exception e) {
            dao.rollback();
              String error = "org.hibernate.exception.ConstraintViolationException: could not execute statement";
            if (e.toString().equals(error)) {
                JOptionPane.showMessageDialog(null, "Ya se ha registrado un cliente con la cédula: "+txCedula.getText()+"\n"+" Favor verifique");
                txCedula.requestFocus();
            }else{
            JOptionPane.showMessageDialog(null, "Se ha producido un error en la carga de datos" );
            } ;
        }
        dao.commit();
       
      
           dispose();
           
             }
           
            
      
    
    

  
    private void cancelar(){
         vaciarCampos();
    }
 
    
    private void vaciarCampos(){
       txNombre.requestFocus();
     
        txNombre.setText("");
        txApellido.setText("");
        txCedula.setText("");
        txTelefono.setText("");
        txDireccion.setText("");
       

        
        
    }
    


    
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cbCiudades;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField txApellido;
    private javax.swing.JTextField txCedula;
    private javax.swing.JTextField txDireccion;
    private javax.swing.JTextField txNombre;
    private javax.swing.JTextField txTelefono;
    // End of variables declaration//GEN-END:variables

    private void recuperarCiudades() {
         daoDistrito = new DaoCiudad();
        ciudades = new ArrayList<>();
        distritos = daoDistrito.recuperarTodo();
              for (int i = 0; i < distritos.size(); i++) {
            ciudades.add(distritos.get(i).getCiudades());

        }
        cbCiudades.setModel(new DefaultComboBoxModel(ciudades.toArray()));

    }


}
