/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lt.views;

import java.awt.Color;
import java.awt.Component;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Logger;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import javax.swing.text.TableView;
import lt.dao.DaoCobros;
import lt.dao.DaoCuota;
import lt.dao.DaoTipoPlan;
import lt.dao.DaoVehiculo;
import lt.interfaces.InterfaceCliente;
import lt.models.Cliente;
import lt.models.Cobranza;
import lt.models.Cuota;
import lt.models.TipoPlan;
import lt.models.Vehiculo;
import lt.tablas.ModeloTablaCobranzas;
import lt.tablas.ModeloTablaCuotas;
import lt.tablas.ModeloTablaVehiculosClienteSeleccionado;
import lt.util.ConnectionHelper;
import lt.util.Utilidad;

/**
 *
 * @author brother
 */
public class CobrosView extends javax.swing.JDialog implements InterfaceCliente {

    private Cliente cliente;
    private Integer codigoCliente;
    private List<Cuota> cuotaslist;
    private List<Cobranza> cobranzaslist;
    private ModeloTablaVehiculosClienteSeleccionado mtVehiculos;
    private ModeloTablaCuotas mtCuotas;
    private ModeloTablaCobranzas mtcoCobranzas;
    private DaoCuota daoCuota;
    private Cuota cuota;
    private double totalCuotas;
    private double montoPagado;
    private DaoCobros daoCobros;
    private List<TipoPlan> poliza;
    private Integer ultimoId;
    private DaoTipoPlan daoPlan;
    private ArrayList<Vehiculo> vehiculos;
    private List<TipoPlan> planes;
    private DaoVehiculo daoVehiculo;
    private Vehiculo vehiculo;
    private TipoPlan plan;
    private int cantidadDeCuotas;
    private int idPlan;
    private LocalDate fechaSeteada;
    private double montoCobrado;
    private double vuelto;

    /**
     * Creates new form CobrosView
     */
    public CobrosView() {
        super();
        initComponents();
        setLocationRelativeTo(this);
        Utilidad.soloNumeros(txMontoPagado);
        estadoInicial(true);
        datePicker1.getComponentDateTextField().setEnabled(false);
        datePicker1.setDateToToday();
        datePicker1.getComponentDateTextField().setDisabledTextColor(Color.BLACK);

        checkColors();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnBuscar = new javax.swing.JButton();
        lblFecha = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblCliente = new javax.swing.JLabel();
        lblIdCobro = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        datePicker1 = new com.github.lgooddatepicker.components.DatePicker();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JButton();
        btnGrabar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        txMontoPagado = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mtCuotas = new ModeloTablaCuotas();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        mtVehiculos = new ModeloTablaVehiculosClienteSeleccionado();
        jTable3 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        mtcoCobranzas = new ModeloTablaCobranzas();
        jTable2 = new javax.swing.JTable();
        lblMontoCuotas = new javax.swing.JLabel();
        btnProcesar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblVuelto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro de Cobros");

        jPanel2.setBackground(new java.awt.Color(45, 118, 232));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBuscar.setBackground(new java.awt.Color(255, 255, 255));
        btnBuscar.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(45, 118, 232));
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lt/images/userNew.png"))); // NOI18N
        btnBuscar.setText("Nuevo");
        btnBuscar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.lightGray, null, null));
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.setFocusPainted(false);
        btnBuscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBuscar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel2.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 50, 120, 70));

        lblFecha.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, -1, 24));

        jLabel3.setText("Cliente:");
        jLabel3.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        jLabel1.setText("Operación:");
        jLabel1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        lblCliente.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblCliente.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(lblCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, 24));

        lblIdCobro.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lblIdCobro.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(lblIdCobro, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, 20));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lt/images/icons8-Cash in Hand Filled-100.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 90));

        jLabel10.setText("Fecha:");
        jLabel10.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, -1, -1));
        jPanel2.add(datePicker1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, -1, -1));

        jPanel3.setBackground(new java.awt.Color(237, 244, 246));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setLayout(new java.awt.GridLayout(1, 5, 5, 3));

        btnCancelar.setBackground(new java.awt.Color(45, 118, 232));
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lt/images/cancelar35.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/lt/images/cancelardisa.png"))); // NOI18N
        btnCancelar.setFocusPainted(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel4.add(btnCancelar);

        btnGrabar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lt/images/guardar35.png"))); // NOI18N
        btnGrabar.setText("Grabar");
        btnGrabar.setBackground(new java.awt.Color(45, 118, 232));
        btnGrabar.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/lt/images/guardardisa.png"))); // NOI18N
        btnGrabar.setFocusPainted(false);
        btnGrabar.setForeground(new java.awt.Color(255, 255, 255));
        btnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarActionPerformed(evt);
            }
        });
        jPanel4.add(btnGrabar);

        btnSalir.setBackground(new java.awt.Color(45, 118, 232));
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lt/images/salir35.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/lt/images/salirdisa.png"))); // NOI18N
        btnSalir.setFocusPainted(false);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel4.add(btnSalir);

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, 460, 58));

        txMontoPagado.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, null));
        txMontoPagado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txMontoPagadoActionPerformed(evt);
            }
        });
        jPanel3.add(txMontoPagado, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 260, 124, 32));

        jLabel6.setText("Monto a Pagar:");
        jLabel6.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 230, -1, -1));

        jLabel5.setText("Total:");
        jLabel5.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 200, -1, -1));

        jScrollPane1.setBorder(null);
        jScrollPane1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jScrollPane1.getViewport().setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        jTable1.setModel(mtCuotas);
        jTable1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jTable1.setRowHeight(25);
        jTable1.setSelectionBackground(new java.awt.Color(92, 132, 228));
        jTable1.setSelectionForeground(new java.awt.Color(255, 255, 255));
        //jTable1.removeColumn(jTable1.getColumnModel().getColumn(5));
        jTable1.getColumnModel().getColumn(5).setMinWidth(0);
        jTable1.getColumnModel().getColumn(5).setMaxWidth(0);
        jTable1.getColumnModel().getColumn(5).setWidth(0);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 590, 180));

        jScrollPane3.getViewport().setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jScrollPane3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane3MouseClicked(evt);
            }
        });

        jTable3.setModel(mtVehiculos);
        jTable3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jTable3.setRowHeight(20);
        jTable3.setSelectionBackground(new java.awt.Color(92, 132, 228));
        jTable3.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable3);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 329, 140));

        jScrollPane2.setBorder(null);
        jScrollPane2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jScrollPane2.getViewport().setBackground(new java.awt.Color(255, 255, 255));

        jTable2.setModel(mtcoCobranzas);
        jTable2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jTable2.setRowHeight(20);
        jTable2.setSelectionBackground(new java.awt.Color(92, 132, 228));
        jTable2.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(jTable2);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 319, 130));

        lblMontoCuotas.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jPanel3.add(lblMontoCuotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 200, -1, 20));

        btnProcesar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lt/images/actualizar35.png"))); // NOI18N
        btnProcesar.setText("Procesar");
        btnProcesar.setBackground(new java.awt.Color(45, 118, 232));
        btnProcesar.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/lt/images/actualizardisa.png"))); // NOI18N
        btnProcesar.setForeground(new java.awt.Color(255, 255, 255));
        btnProcesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcesarActionPerformed(evt);
            }
        });
        jPanel3.add(btnProcesar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 300, -1, 50));

        jLabel7.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabel7.setText("Últimos Pagos");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel8.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabel8.setText("Vehículos");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, -1, -1));

        jLabel9.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabel9.setText("Cuotas");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));
        jPanel3.add(lblVuelto, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 370, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        buscadorClienteVehiculo busCliente = new buscadorClienteVehiculo();
        busCliente.setInterfaceCliente(this);

        buscadorClienteVehiculo.btnSeleccionar.setEnabled(true);

        busCliente.setVisible(true);

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked

    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed

    }//GEN-LAST:event_jTable1KeyPressed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        registrarCobroCuota();
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarActionPerformed
        guardar();
    }//GEN-LAST:event_btnGrabarActionPerformed

    private void txMontoPagadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txMontoPagadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txMontoPagadoActionPerformed

    private void btnProcesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcesarActionPerformed
        if (txMontoPagado.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe ingresar un monto para procesar");
            txMontoPagado.requestFocus();
        } else {

            actualizarTablaCobros();
        }
    }//GEN-LAST:event_btnProcesarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        cancelar();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void jScrollPane3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane3MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jScrollPane3MouseClicked

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
        // TODO add your handling code here:
        setearTablaCobros(jTable3.getSelectedRow());
        setearTablaPagos(jTable3.getSelectedRow());
    }//GEN-LAST:event_jTable3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        ConnectionHelper.setUp();

    
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CobrosView dialog = new CobrosView();
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGrabar;
    private javax.swing.JButton btnProcesar;
    private javax.swing.JButton btnSalir;
    private com.github.lgooddatepicker.components.DatePicker datePicker1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblIdCobro;
    private javax.swing.JLabel lblMontoCuotas;
    private javax.swing.JLabel lblVuelto;
    private javax.swing.JTextField txMontoPagado;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
        lblCliente.setText(cliente.getNombre() + " " + cliente.getApellido());
        codigoCliente = cliente.getCodigo();
        mostrarVehiculosDelCliente();

        recuperarUltimoid();
        estadoBotonesNuevo();
        btnBuscar.setEnabled(false);
        jTable3.setEnabled(true);
        lblFecha.setText(datePicker1.getDateStringOrEmptyString());
        datePicker1.setEnabled(false);

    }

    private void mostrarVehiculosDelCliente() {

        daoPlan = new DaoTipoPlan();
        vehiculos = new ArrayList<Vehiculo>();
        planes = daoPlan.recuperarPolizaActivaPorIdCliente(cliente);
        for (int i = 0; i < planes.size(); i++) {
            daoVehiculo = new DaoVehiculo();
            vehiculo = daoVehiculo.recuperarPorId(planes.get(i).getVehiculo().getCodigo());
            vehiculos.add(vehiculo);
        }
        mtVehiculos.setLista(vehiculos);
        jTable3.setModel(mtVehiculos);
    }

    private void setearTablaCobros(int index) {
        if (index < 0) {
            return;
        }
        vehiculo = vehiculos.get(index);

        daoPlan = new DaoTipoPlan();
        plan = daoPlan.recuperarPolizaPorIdVehiculo(vehiculo);
        idPlan = plan.getCodigo();
        cantidadDeCuotas = plan.getCantidadCuotas();
        daoCuota = new DaoCuota();
        cuotaslist = daoCuota.recuperarPorPolizaSoloFalse(plan);
        String codigo = vehiculo.getCodigo().toString();

        mtCuotas.setLista(cuotaslist);
        ordenarColumnasPorCuota();

        centrarValores();
        jTable1.setModel(mtCuotas);

    }

    private void setearTablaPagos(int index) {
        if (index < 0) {
            return;
        }
        daoCobros = new DaoCobros();
        vehiculo = vehiculos.get(index);
        cobranzaslist = daoCobros.recuperarCuentaDeVehiculo(vehiculo.getCodigo());
        mtcoCobranzas.setLista(cobranzaslist);
        jTable2.setModel(mtcoCobranzas);
    }

    private void ordenarColumnasPorCuota() {
        TableRowSorter<TableModel> sorter = new TableRowSorter<>(jTable1.getModel());
        jTable1.setRowSorter(sorter);
        List<RowSorter.SortKey> sortKeys = new ArrayList<>();
        //int columnIndexToSort = 0;
        sortKeys.add(new RowSorter.SortKey(5, SortOrder.ASCENDING));
        sorter.setSortKeys(sortKeys);
        sorter.sort();
    }

    private void registrarCobroCuota() {

        Double sumaMontoCuotas = 0.0;
        habilitarProcesar();
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            if (jTable1.getValueAt(i, 4).equals(true)) {
                sumaMontoCuotas += Utilidad.formatoValorNumeroStringADouble(String.valueOf(jTable1.getValueAt(i, 1)));
                jTable3.setEnabled(false);

            }
            lblMontoCuotas.setText(Utilidad.formatoValorNumeroDoubleAString(sumaMontoCuotas));

        }
    }

    private void habilitarProcesar() {
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            if (jTable1.isColumnSelected(4)) {
                btnProcesar.setEnabled(true);
                txMontoPagado.setEnabled(true);
                break;

            }
        }
    }

    private void actualizarTablaCobros() {
        montoPagado = Utilidad.formatoValorNumeroStringADouble(txMontoPagado.getText());
        double montoCuota = 0.0;
        //montocobrado sumara cuanto se paga
        montoCobrado = 0.0;
        btnGrabar.setEnabled(true);
        btnProcesar.setEnabled(false);
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            if (jTable1.getValueAt(i, 4).equals(true)) {
                montoCuota = Utilidad.formatoValorNumeroStringADouble(jTable1.getValueAt(i, 1).toString());
                if (montoCuota <= montoPagado) {
                    montoCobrado += montoCuota;
                    jTable1.setValueAt(0, i, 1);
                    montoPagado -= montoCuota;
                } else {
                    montoCobrado = Utilidad.formatoValorNumeroStringADouble(txMontoPagado.getText());
                    montoCuota = montoCuota - montoPagado;
                    jTable1.setValueAt(Utilidad.formatoValorNumeroDoubleAString(montoCuota), i, 1);
                }

            }
        }
        vuelto = Utilidad.formatoValorNumeroStringADouble(txMontoPagado.getText()) - Utilidad.formatoValorNumeroStringADouble(lblMontoCuotas.getText());
        if (vuelto > 0) {
            lblVuelto.setText("Vuelto: GS " + Utilidad.formatoValorNumeroDoubleAString(vuelto));
        }
    }

    private void guardar() {

        for (int i = 0; i < jTable1.getRowCount(); i++) {
            if (jTable1.getValueAt(i, 4).equals(true)) {

                daoCuota = new DaoCuota();

                cuota = daoCuota.recuperarPorId(Integer.parseInt(jTable1.getValueAt(i, 5).toString()));
                double saldo = Utilidad.formatoValorNumeroStringADouble(jTable1.getValueAt(i, 1).toString());
                cuota.setSaldoCuota(saldo);
                System.out.println("valor de la celda" + jTable1.getValueAt(i, 1));
                if (Double.parseDouble(jTable1.getValueAt(i, 1).toString()) == 0) {
                    cuota.setEstadoCuotas(true);

                }
                try {
                    daoCuota = new DaoCuota();
                    daoCuota.actualizar(cuota);
                    daoCuota.commit();
                    verificarVigenciaContrato();

                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "Error al guardar la cuota nro " + jTable1.getValueAt(i, 0).toString() + "\n" + ex);
                    daoCuota.rollback();
                }

            }
        }

        //aca empieza el metodo de guardar el cobro
        Cobranza cobro = new Cobranza();
        cobro.setCliente(cliente);
        cobro.setFechaCobro(LocalDate.parse(lblFecha.getText()));
        cobro.setMontoCobro(montoCobrado);
        cobro.setVehiculo(vehiculo);

        //iicializar el dao
        daoCobros = new DaoCobros();
        try {
            daoCobros.insertar(cobro);
            daoCobros.commit();
            recuperarTodo();

        } catch (Exception e) {
            Logger.getLogger("Error Registrado al guardar cobros" + e);
            daoCobros.rollback();

        }
        cuotaslist = new ArrayList<>();
        mtCuotas.setLista(cuotaslist);
        jTable1.setModel(mtCuotas);
        cobranzaslist = new ArrayList<>();
        mtcoCobranzas.setLista(cobranzaslist);
        jTable2.setModel(mtcoCobranzas);
        vehiculos = new ArrayList<>();
        mtVehiculos.setLista(vehiculos);
        jTable3.setModel(mtVehiculos);

        limpiarCampos();
        estadoInicial(true);

    }

    private void recuperarTodo() {
        daoCuota = new DaoCuota();
        cuotaslist = daoCuota.recuperarSoloFalse();
        mtCuotas.setLista(cuotaslist);
    }

    private void nuevo() {
        LocalDate hoy = LocalDate.now();
        lblFecha.setText(hoy.toString());
        recuperarUltimoid();

    }

    private void estadoInicial(boolean estado) {

        txMontoPagado.setEnabled(!estado);
        btnGrabar.setEnabled(!estado);
        btnProcesar.setEnabled(!estado);
        btnSalir.setEnabled(estado);
        btnBuscar.setEnabled(estado);
        btnCancelar.setEnabled(!estado);
        jTable1.setEnabled(estado);
        datePicker1.setEnabled(estado);

    }

    private void recuperarUltimoid() {
        daoCobros = new DaoCobros();
        ultimoId = daoCobros.recuperarUltimoID();
        lblIdCobro.setText(ultimoId + 1 + "");
    }

    private void estadoBotonesNuevo() {
        btnCancelar.setEnabled(true);
        btnBuscar.setEnabled(true);

    }

    private void cancelar() {
        cuotaslist = new ArrayList<>();
        mtCuotas.setLista(cuotaslist);
        jTable1.setModel(mtCuotas);
        cobranzaslist = new ArrayList<>();
        mtcoCobranzas.setLista(cobranzaslist);
        jTable2.setModel(mtcoCobranzas);
        vehiculos = new ArrayList<>();
        mtVehiculos.setLista(vehiculos);
        jTable3.setModel(mtVehiculos);

        limpiarCampos();
        estadoInicial(true);
    }

    private void limpiarCampos() {
        lblIdCobro.setText("");
        lblFecha.setText("");
        lblMontoCuotas.setText("");
        txMontoPagado.setText("");
        lblCliente.setText("");
        lblVuelto.setText("");

    }

    private void centrarValores() {
        //centra los valores, tambien cambiara el color de la fila
        DefaultTableCellRenderer center = new DefaultTableCellRenderer();
        center.setHorizontalAlignment(JLabel.CENTER);
        for (int i = 0; i < jTable1.getColumnCount() - 2; i++) {
            jTable1.getColumnModel().getColumn(i).setCellRenderer(center);
        }
    }

    private void verificarVigenciaContrato() {
        daoCuota = new DaoCuota();
        cuotaslist = daoCuota.recuperarPorPolizaSoloFalse(plan);
        if (cuotaslist.size() == 0) {
            daoPlan = new DaoTipoPlan();
            plan = daoPlan.recuperarPorId(idPlan);
            plan.setEstadoActivo(false);
            daoPlan = new DaoTipoPlan();
            try {
                daoPlan.actualizar(plan);
                daoPlan.commit();
            } catch (Exception e) {
                System.out.println("Error al cancelar plan: " + e);
                daoPlan.rollback();
            }
        }
    }

    private void checkColors() {
        if (btnBuscar.isEnabled()) {
            btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    btnBuscar.setBackground(new java.awt.Color(255, 130, 79));
                    btnBuscar.setForeground(Color.WHITE);
                }

                public void mouseExited(java.awt.event.MouseEvent evt) {
                    btnBuscar.setBackground(new java.awt.Color(255, 255, 255));
                    btnBuscar.setForeground(new java.awt.Color(25, 118, 232));
                }
            });
        }
    }

}
