/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lt.views;

import java.awt.Button;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.KeyStroke;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableColumnModel;
import lt.dao.DaoCiudad;
import lt.dao.DaoCliente;
import lt.dao.DaoDepartamento;
import lt.dao.DaoVehiculo;
import lt.interfaces.InterfaceBuscadorVehiculo;
import lt.models.Cliente;
import lt.models.Departamentos;
import lt.models.Distritos;
import lt.models.Vehiculo;

import lt.tablas.ModeloTablaCliente;
import lt.tablas.ModeloTablaVehiculosCliente;
import lt.util.ConnectionHelper;
import lt.util.Utilidad;

/**
 *
 * @author brother
 */
public class CustomerView extends javax.swing.JDialog implements InterfaceBuscadorVehiculo {

    private ModeloTablaCliente mtCliente;
    private ModeloTablaVehiculosCliente mtVehiculoCliente;

    private Cliente cliente;
    private List<Cliente> listaCliente;
    private String accion;
    private DaoCliente dao;
    private InterfaceBuscadorVehiculo buscadorVehiculo;
    private Vehiculo vehiculo;
    private DaoVehiculo daoVehiculo;
    private DaoDepartamento daoDepartamento;
    private List<Departamentos> departamentos;
    private DaoCiudad daoDistrito;
    private List<Distritos> distritos;
    private ArrayList<Object> ciudades;
    private Distritos distrito;
    private Departamentos departamento;
    private Integer dtoIndex;
    private int cityIndex;

    public CustomerView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(this);
        estadoInicial(true);
        Utilidad.soloLetras(txApellido);
        Utilidad.soloNumeros(txCedula);
        //Utilidad.soloLetras(txCiudad);
        Utilidad.soloLetras(txDireccion);
        Utilidad.soloLetras(txNombre);
        Utilidad.soloNumeros(txTelefono);
        //teclas rapidas
        agregarAbreviado(this);
        limpiarAbreviado(this);
        guardarAbreviado(this);
        eliminarAbreviado(this);
        //mayusculas       
         txBuscar.setDocument(new Utilidad());
        txApellido.setDocument(new Utilidad());
        txDireccion.setDocument(new Utilidad());
        txNombre.setDocument(new Utilidad());
        recuperarTodo();
        formateoTabla();

        checkColors();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        head = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txBuscar = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        body = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mtCliente = new ModeloTablaCliente();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        mtVehiculoCliente = new ModeloTablaVehiculosCliente();
        jTable2 = new javax.swing.JTable();
        btnCancelar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txApellido = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txCedula = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txTelefono = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txDireccion = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        cbCiudades = new javax.swing.JComboBox<>();
        cbDepartamento = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setModal(true);
        setSize(new java.awt.Dimension(800, 600));

        jPanel1.setBackground(new java.awt.Color(237, 244, 246));
        jPanel1.setMaximumSize(new java.awt.Dimension(800, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        head.setBackground(new java.awt.Color(45, 118, 232));
        head.setForeground(new java.awt.Color(238, 238, 232));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lt/images/cliente.png"))); // NOI18N
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Consulta y Registro de Clientes");

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Código:");

        lblCodigo.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblCodigo.setForeground(new java.awt.Color(255, 255, 255));

        txBuscar.setBackground(new java.awt.Color(45, 118, 232));
        txBuscar.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txBuscar.setForeground(new java.awt.Color(255, 255, 255));
        txBuscar.setBorder(null);
        txBuscar.setCaretColor(new java.awt.Color(255, 255, 255));
        txBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txBuscarActionPerformed(evt);
            }
        });
        txBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txBuscarKeyPressed(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lt/images/search_20px_1.png"))); // NOI18N

        javax.swing.GroupLayout headLayout = new javax.swing.GroupLayout(head);
        head.setLayout(headLayout);
        headLayout.setHorizontalGroup(
            headLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGroup(headLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headLayout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jLabel2)
                        .addContainerGap())
                    .addGroup(headLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCodigo)
                        .addGroup(headLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(headLayout.createSequentialGroup()
                                .addGap(229, 229, 229)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 206, Short.MAX_VALUE)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(121, 121, 121))))))
        );
        headLayout.setVerticalGroup(
            headLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
            .addGroup(headLayout.createSequentialGroup()
                .addGroup(headLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(headLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headLayout.createSequentialGroup()
                                .addGroup(headLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(lblCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(2, 2, 2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headLayout.createSequentialGroup()
                                .addComponent(txBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );

        jPanel1.add(head, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 120));

        body.setBackground(new java.awt.Color(237, 244, 246));
        body.setMaximumSize(new java.awt.Dimension(800, 480));
        body.setMinimumSize(new java.awt.Dimension(800, 480));
        body.setPreferredSize(new java.awt.Dimension(800, 480));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.getViewport().setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jTable1.setModel(mtCliente);
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.setRowHeight(22);
        jTable1.setBackground(new java.awt.Color(255, 255, 255));
        jTable1.setSelectionBackground(new java.awt.Color(92, 132, 228));
        jTable1.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jScrollPane2.getViewport().setBackground(new java.awt.Color(255, 255, 255));

        jTable2.setModel(mtVehiculoCliente);
        jScrollPane2.setViewportView(jTable2);

        btnCancelar.setBackground(new java.awt.Color(25, 118, 232));
        btnCancelar.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lt/images/cancelar35.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/lt/images/cancelardisa.png"))); // NOI18N
        btnCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancelar.setMaximumSize(new java.awt.Dimension(120, 75));
        btnCancelar.setMinimumSize(new java.awt.Dimension(120, 75));
        btnCancelar.setPreferredSize(new java.awt.Dimension(120, 75));
        btnCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnNuevo.setBackground(new java.awt.Color(25, 118, 232));
        btnNuevo.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnNuevo.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lt/images/nuevo35.png"))); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/lt/images/nuevodisa.png"))); // NOI18N
        btnNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNuevo.setMaximumSize(new java.awt.Dimension(120, 75));
        btnNuevo.setMinimumSize(new java.awt.Dimension(120, 75));
        btnNuevo.setPreferredSize(new java.awt.Dimension(120, 75));
        btnNuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnModificar.setBackground(new java.awt.Color(25, 118, 232));
        btnModificar.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(255, 255, 255));
        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lt/images/actualizar35.png"))); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/lt/images/actualizardisa.png"))); // NOI18N
        btnModificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnModificar.setMaximumSize(new java.awt.Dimension(120, 75));
        btnModificar.setMinimumSize(new java.awt.Dimension(120, 75));
        btnModificar.setPreferredSize(new java.awt.Dimension(120, 75));
        btnModificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnGuardar.setBackground(new java.awt.Color(25, 118, 232));
        btnGuardar.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lt/images/guardar35.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/lt/images/guardardisa.png"))); // NOI18N
        btnGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGuardar.setMaximumSize(new java.awt.Dimension(120, 75));
        btnGuardar.setMinimumSize(new java.awt.Dimension(120, 75));
        btnGuardar.setPreferredSize(new java.awt.Dimension(120, 75));
        btnGuardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        btnGuardar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnGuardarKeyPressed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(25, 118, 232));
        btnSalir.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lt/images/salir35.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/lt/images/salirdisa.png"))); // NOI18N
        btnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalir.setMaximumSize(new java.awt.Dimension(120, 75));
        btnSalir.setMinimumSize(new java.awt.Dimension(120, 75));
        btnSalir.setPreferredSize(new java.awt.Dimension(120, 75));
        btnSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(237, 244, 246));

        txNombre.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txNombre.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, null));
        txNombre.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txNombre.setDisabledTextColor(new java.awt.Color(77, 85, 92));
        txNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txNombreActionPerformed(evt);
            }
        });
        txNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txNombreKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel4.setText("Nombre:");

        txApellido.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txApellido.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, null));
        txApellido.setDisabledTextColor(new java.awt.Color(77, 85, 92));
        txApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txApellidoActionPerformed(evt);
            }
        });
        txApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txApellidoKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel3.setText("Apellido:");

        txCedula.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txCedula.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, null));
        txCedula.setDisabledTextColor(new java.awt.Color(77, 85, 92));
        txCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txCedulaActionPerformed(evt);
            }
        });
        txCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txCedulaKeyPressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel5.setText("Cédula:");

        txTelefono.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txTelefono.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, null));
        txTelefono.setDisabledTextColor(new java.awt.Color(77, 85, 92));
        txTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txTelefonoKeyPressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel6.setText("Teléfono:");

        txDireccion.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txDireccion.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, null));
        txDireccion.setDisabledTextColor(new java.awt.Color(77, 85, 92));
        txDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txDireccionActionPerformed(evt);
            }
        });
        txDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txDireccionKeyPressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel7.setText("Dirección:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                    .addComponent(txApellido)
                    .addComponent(txTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                    .addComponent(txCedula)
                    .addComponent(txDireccion))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)))
        );

        btnEliminar.setBackground(new java.awt.Color(25, 118, 232));
        btnEliminar.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lt/images/eliminar35.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setDisabledSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/lt/images/eliminardisa.png"))); // NOI18N
        btnEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminar.setMaximumSize(new java.awt.Dimension(120, 75));
        btnEliminar.setMinimumSize(new java.awt.Dimension(120, 75));
        btnEliminar.setPreferredSize(new java.awt.Dimension(120, 75));
        btnEliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        cbCiudades.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        cbCiudades.setRenderer(new DefaultListCellRenderer() {
            @Override
            public void paint(Graphics g) {
                setForeground(Color.BLACK);
                super.paint(g);
            }
        });
        cbCiudades.setModel(new javax.swing.DefaultComboBoxModel<>());
        cbCiudades.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbCiudadesKeyPressed(evt);
            }
        });

        cbDepartamento.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        cbDepartamento.setRenderer(new DefaultListCellRenderer() {
            @Override
            public void paint(Graphics g) {
                setForeground(Color.BLACK);
                super.paint(g);
            }
        });
        cbDepartamento.setModel(new javax.swing.DefaultComboBoxModel<>());
        cbDepartamento.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbDepartamentoItemStateChanged(evt);
            }
        });
        cbDepartamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbDepartamentoKeyPressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel9.setText("Departamento:");

        jLabel10.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel10.setText("Ciudad:");

        javax.swing.GroupLayout bodyLayout = new javax.swing.GroupLayout(body);
        body.setLayout(bodyLayout);
        bodyLayout.setHorizontalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bodyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(cbDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbCiudades, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(197, 197, 197))
            .addGroup(bodyLayout.createSequentialGroup()
                .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, bodyLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, bodyLayout.createSequentialGroup()
                        .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        bodyLayout.setVerticalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyLayout.createSequentialGroup()
                .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bodyLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(bodyLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bodyLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbCiudades, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bodyLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnModificar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNuevo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        jPanel1.add(body, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 780, 470));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        cancelar();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        nuevo();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        modificar();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (validar()) {
            guardar();
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void txDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txDireccionActionPerformed

    private void txApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txApellidoActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        eliminar();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void cbDepartamentoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbDepartamentoItemStateChanged
        recuperarCiudades();
    }//GEN-LAST:event_cbDepartamentoItemStateChanged

    private void txNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txNombreActionPerformed

    private void txCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txCedulaActionPerformed

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked

    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        seleccionarObjeto(jTable1.getSelectedRow());
    }//GEN-LAST:event_jTable1MouseClicked

    private void txBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txBuscarKeyPressed
           if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            buscar();
        }
    }//GEN-LAST:event_txBuscarKeyPressed

    private void txBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txBuscarActionPerformed

    private void txNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txNombreKeyPressed
        Utilidad.moverConEnter(evt, txApellido);
    }//GEN-LAST:event_txNombreKeyPressed

    private void txApellidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txApellidoKeyPressed
        Utilidad.moverConEnter(evt, txCedula);
    }//GEN-LAST:event_txApellidoKeyPressed

    private void txCedulaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txCedulaKeyPressed
        Utilidad.moverConEnter(evt, txTelefono);
    }//GEN-LAST:event_txCedulaKeyPressed

    private void txTelefonoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txTelefonoKeyPressed
        Utilidad.moverConEnter(evt, txDireccion);
    }//GEN-LAST:event_txTelefonoKeyPressed

    private void txDireccionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txDireccionKeyPressed
        Utilidad.moverConEnter(evt, cbDepartamento);
    }//GEN-LAST:event_txDireccionKeyPressed

    private void cbDepartamentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbDepartamentoKeyPressed
        Utilidad.moverConEnter(evt, cbCiudades);
    }//GEN-LAST:event_cbDepartamentoKeyPressed

    private void cbCiudadesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbCiudadesKeyPressed
        Utilidad.moverConEnter(evt, btnGuardar);
    }//GEN-LAST:event_cbCiudadesKeyPressed

    private void btnGuardarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnGuardarKeyPressed
                 if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
               if (validar()) {
            guardar();
        }
        }
    }//GEN-LAST:event_btnGuardarKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        ConnectionHelper.setUp();
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }


        //</editor-fold>


        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CustomerView dialog = new CustomerView(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel body;
    private static javax.swing.JButton btnCancelar;
    private static javax.swing.JButton btnEliminar;
    private static javax.swing.JButton btnGuardar;
    private static javax.swing.JButton btnModificar;
    private static javax.swing.JButton btnNuevo;
    private static javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cbCiudades;
    private javax.swing.JComboBox<String> cbDepartamento;
    private javax.swing.JPanel head;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JTextField txApellido;
    private javax.swing.JTextField txBuscar;
    private javax.swing.JTextField txCedula;
    private javax.swing.JTextField txDireccion;
    private javax.swing.JTextField txNombre;
    private javax.swing.JTextField txTelefono;
    // End of variables declaration//GEN-END:variables
//METODOS
    private void seleccionarObjeto(int index) {
        if (index < 0) {
            return;
        }

        cliente = listaCliente.get(index);
        daoDepartamento = new DaoDepartamento();
        departamento = daoDepartamento.recuperarPorId(cliente.getDistrito().getDepartamentoId().getId());

        distrito = cliente.getDistrito();
        recuperarDepartamentos();
        cbDepartamento.setSelectedItem(departamento.getDepartamentos());
        mostrarCiudades();
        cbCiudades.setSelectedItem(distrito.getCiudades());
        lblCodigo.setText(cliente.getCodigo() + "");
        txNombre.setText(cliente.getNombre());
        txApellido.setText(cliente.getApellido());
        txCedula.setText(cliente.getCin() + "");
        txTelefono.setText(cliente.getTelefono() + "");
        txDireccion.setText(cliente.getDireccion());
        daoVehiculo = new DaoVehiculo();
        List<Vehiculo> vehiculos = daoVehiculo.recuperarVehiculoPorIdCliente(cliente);
        mtVehiculoCliente.setLista(vehiculos);
        jTable2.setModel(mtVehiculoCliente);

        estadoBotonesSeleccionarObjetos();

    }

    private void guardar() {
        daoDistrito = new DaoCiudad();
        distrito = daoDistrito.recuperarDistritosPorParametro(cbCiudades.getSelectedItem().toString());
        if (accion.equals("NUEVO")) {
            cliente = new Cliente();
        }
        cliente.setNombre(txNombre.getText());
        cliente.setApellido(txApellido.getText());
        cliente.setCin(Integer.parseInt(txCedula.getText()));
        cliente.setTelefono(txTelefono.getText());
        cliente.setDistrito(distrito);
        cliente.setDireccion(txDireccion.getText());

        dao = new DaoCliente();
        try {
            if (accion.equals("NUEVO")) {
                dao.insertar(cliente);
            } else {
                dao.actualizar(cliente);
            }
            dao.commit();

            recuperarTodo();
            estadoInicial(true);
            vaciarCampos();
        } catch (Exception e) {
            dao.rollback();
            String error = "org.hibernate.exception.ConstraintViolationException: could not execute statement";
            if (e.toString().equals(error)) {
                JOptionPane.showMessageDialog(null, "Ya se ha registrado un cliente con la cédula: " + txCedula.getText() + "\n" + " Favor verifique");
                txCedula.requestFocus();
            } else {
                JOptionPane.showMessageDialog(null, "Se ha producido un error en la carga de datos");
            };
        }
        txBuscar.setEnabled(true);
        txBuscar.requestFocus();
    }

    private boolean validar() {
        boolean validar = false;
        if (txNombre.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "No se puede guardar un cliente sin Nombre, favor verifique.");
            txNombre.requestFocus();
        } else if (txApellido.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "No se puede guardar un cliente sin Apellido, favor verifique.");
            txApellido.requestFocus();
        } else if (txCedula.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "No se puede guardar un cliente sin Documento, favor verifique.");
            txCedula.requestFocus();
        } else if (txDireccion.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "No se puede guardar un cliente sin Domicilio, favor verifique.");
            txDireccion.requestFocus();
        } else if (txTelefono.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "No se puede guardar un cliente sin N° de teléfono , favor verifique.");
            txTelefono.requestFocus();
        } else {
            validar = true;
        }

        return validar;

    }

    private void nuevo() {
        accion = "NUEVO";

        estadoBotonesNuevoUpdate();
        vaciarCampos();
        recuperarDepartamentos();
        cbDepartamento.setSelectedIndex(13);        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        recuperarCiudades();
        
        setearIdNuevo();
    }

    private void setearIdNuevo() {
        dao = new DaoCliente();
        Integer id = dao.recuperarUltimoID() + 1;
        lblCodigo.setText(id + "");
    }

    private void buscar() {
        dao = new DaoCliente();


        String dato = txBuscar.getText();
        
        boolean codigo = false;
        for (int i = 0; i < dato.length(); i++) {
            if (Character.isDigit(dato.charAt(i))) {
                codigo = true;
            }
        }
        if (codigo) {
            dao.recuperarPorId(Integer.parseInt(dato));

        } else {
            listaCliente = dao.recuperarPorFiltro(dato);

        }

        mtCliente.setLista(listaCliente);
        btnCancelar.setEnabled(true);
    }

    private void cancelar() {
        cbCiudades.setModel(new DefaultComboBoxModel<>());
        cbDepartamento.setModel(new DefaultComboBoxModel<>());
        estadoInicial(true);
        vaciarCampos();
        txBuscar.setEnabled(true);
        txBuscar.requestFocus();
        btnCancelar.setEnabled(true);
    }

    private void eliminar() {
        int index = jTable1.getSelectedRow();
        if (index < 0) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un Cliente");
            return;
        }
        cliente = listaCliente.get(index);
        int result = JOptionPane.showConfirmDialog(null,
                "Esta seguro que desea eliminar el cliente \n " + cliente.getNombre() + " " + cliente.getApellido(),
                "Atención", JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION) {
            dao = new DaoCliente();
            try {
                dao.eliminar(cliente);
                dao.commit();
                recuperarTodo();
                vaciarCampos();
            } catch (Exception e) {
                dao.rollback();
                JOptionPane.showMessageDialog(null, "El cliente que desea eliminar posee vehículo(s) registrado(s). \n"
                        + " La operación no puede realizarse.");
            }
        }

    }

    private void recuperarTodo() {
        dao = new DaoCliente();
        listaCliente = dao.recuperarTodo();
        mtCliente.setLista(listaCliente);
    }

    private void vaciarCampos() {
        txNombre.requestFocus();
        lblCodigo.setText("");
        txNombre.setText("");
        txApellido.setText("");
        txCedula.setText("");
        txTelefono.setText("");
        txDireccion.setText("");
        txBuscar.setText("");

    }

    private void estadoInicial(Boolean estado) {
        //textFields
        cbCiudades.setModel(new DefaultComboBoxModel<>());
        cbDepartamento.setModel(new DefaultComboBoxModel<>());
        cbCiudades.setEnabled(!estado);
        cbDepartamento.setEnabled(!estado);
        txNombre.setEnabled(!estado);
        txApellido.setEnabled(!estado);
        txCedula.setEnabled(!estado);
        txTelefono.setEnabled(!estado);
        txDireccion.setEnabled(!estado);
        //botones
        btnNuevo.setEnabled(estado);
        btnEliminar.setEnabled(!estado);
        btnGuardar.setEnabled(!estado);
        btnCancelar.setEnabled(!estado);
        btnModificar.setEnabled(!estado);
        //tabla de cliente
        jTable1.clearSelection();
        jTable1.setEnabled(estado);
    }

    private void estadoBotonesSeleccionarObjetos() {
        //botones
        btnNuevo.setEnabled(false);
        // btnBuscar.setEnabled(true);
        btnEliminar.setEnabled(true);
        btnGuardar.setEnabled(false);
        btnCancelar.setEnabled(true);
        btnModificar.setEnabled(true);
        txBuscar.setText("");
    }

    private void modificar() {
        accion = "MODIFICAR";

        estadoBotonesNuevoUpdate();

    }

    private void formateoTabla() {
        TableColumnModel columnModel = jTable1.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(200);
        columnModel.getColumn(1).setPreferredWidth(100);
        columnModel.getColumn(2).setPreferredWidth(140);
        columnModel.getColumn(3).setPreferredWidth(108);
        jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        jTable1.doLayout();

        //alineamiento de celdas
        DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
        tcr.setHorizontalAlignment(SwingConstants.RIGHT);

        // jTable1.getColumnModel().getColumn(3).setCellRenderer(tcr);
    }

    private void formateoTablaVehiculo() {
        TableColumnModel columnModel = jTable2.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(200);
        columnModel.getColumn(1).setPreferredWidth(100);
        columnModel.getColumn(2).setPreferredWidth(140);
        columnModel.getColumn(3).setPreferredWidth(108);
        jTable2.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        jTable2.doLayout();

        //alineamiento de celdas
        DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
        tcr.setHorizontalAlignment(SwingConstants.RIGHT);

        // jTable1.getColumnModel().getColumn(3).setCellRenderer(tcr);
    }

    @Override
    public void setVehiculo(Vehiculo vehiculo) {
        this.vehiculo = vehiculo;

    }

    private void estadoBotonesNuevoUpdate() {
        cbCiudades.setEnabled(true);
        cbDepartamento.setEnabled(true);
        btnNuevo.setEnabled(false);
        btnEliminar.setEnabled(false);
        btnGuardar.setEnabled(true);
        btnCancelar.setEnabled(true);
        btnModificar.setEnabled(false);
        txBuscar.setEnabled(false);
        txNombre.setEnabled(true);
        txApellido.setEnabled(true);
        txCedula.setEnabled(true);
        txDireccion.setEnabled(true);
        txTelefono.setEnabled(true);
        //txCiudad.setEnabled(true);
        txNombre.requestFocus();
        jTable1.clearSelection();
        jTable1.setEnabled(false);

    }

    private void checkColors() {
//       if(jButton3.isEnabled()){
//jButton3.addMouseListener(new java.awt.event.MouseAdapter(){
// public void mouseEntered(java.awt.event.MouseEvent evt) {
//        jButton3.setBackground(new java.awt.Color(255, 130, 79));
//        jButton3.setForeground(Color.WHITE);
//    }
//
//    public void mouseExited(java.awt.event.MouseEvent evt) {
//        jButton3.setBackground(new java.awt.Color(25, 118, 232));
//    }
//});
//    }
    }

    @Override
    public List<Vehiculo> listaDeVehiculos() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void recuperarDepartamentos() {
        daoDepartamento = new DaoDepartamento();
        departamentos = daoDepartamento.recuperarTodo();
        ArrayList<Object> dtos = new ArrayList<>();
        for (int i = 0; i < departamentos.size(); i++) {
            dtos.add(departamentos.get(i).getDepartamentos());
        }
        cbDepartamento.setModel(new DefaultComboBoxModel(dtos.toArray()));

    }

    private void recuperarCiudades() {
        int idDepartamento = cbDepartamento.getSelectedIndex() + 1;
        daoDistrito = new DaoCiudad();
        ciudades = new ArrayList<>();
        distritos = daoDistrito.recuperarDistritosPorDepartamento(idDepartamento);

        for (int i = 0; i < distritos.size(); i++) {
            ciudades.add(distritos.get(i).getCiudades());

        }
        cbCiudades.setModel(new DefaultComboBoxModel(ciudades.toArray()));
        

    }

    private void mostrarCiudades() {
        int idDepartamento = cbDepartamento.getSelectedIndex() + 1;
        daoDistrito = new DaoCiudad();
        ciudades = new ArrayList<>();
        distritos = daoDistrito.recuperarDistritosPorDepartamento(idDepartamento);

        for (int i = 0; i < distritos.size(); i++) {
            ciudades.add(distritos.get(i).getCiudades());

        }
        cbCiudades.setModel(new DefaultComboBoxModel(ciudades.toArray()));

    }
     //Metodo abreviado para agregar un registro
    public static void agregarAbreviado(final JDialog dialog) {
        ActionListener listener = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                btnNuevo.doClick();

            }
        };
        dialog.getRootPane().registerKeyboardAction(listener, KeyStroke.getKeyStroke(KeyEvent.VK_F2, 0), JComponent.WHEN_IN_FOCUSED_WINDOW);
    }

    //Metodo abreviado para buscar un registro
//    public static void buscarAbreviado(final JDialog dialog) {
//        ActionListener listener = new ActionListener() {
//            @Override
//            public void actionPerformed(ActionEvent e) {
//                btnBusquedaFun.doClick();
//
//            }
//        };
//        dialog.getRootPane().registerKeyboardAction(listener, KeyStroke.getKeyStroke(KeyEvent.VK_F3, 0), JComponent.WHEN_IN_FOCUSED_WINDOW);
//    }

    //Metodo abreviado para Limpiar el formulario
    public static void limpiarAbreviado(final JDialog dialog) {
        ActionListener listener = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                btnCancelar.doClick();

            }
        };
        dialog.getRootPane().registerKeyboardAction(listener, KeyStroke.getKeyStroke(KeyEvent.VK_F5, 0), JComponent.WHEN_IN_FOCUSED_WINDOW);
    }

    //Metodo abreviado para Limpiar el formulario
    public static void eliminarAbreviado(final JDialog dialog) {
        ActionListener listener = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                btnEliminar.doClick();

            }
        };
        dialog.getRootPane().registerKeyboardAction(listener, KeyStroke.getKeyStroke(KeyEvent.VK_F8, 0), JComponent.WHEN_IN_FOCUSED_WINDOW);
    }

    //Metodo abreviado para Limpiar el formulario
    public static void guardarAbreviado(final JDialog dialog) {
        ActionListener listener = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                btnGuardar.doClick();

            }
        };
        dialog.getRootPane().registerKeyboardAction(listener, KeyStroke.getKeyStroke(KeyEvent.VK_F10, 0), JComponent.WHEN_IN_FOCUSED_WINDOW);
    }

}
