/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lt.views;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.time.Instant;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeFormatterBuilder;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableColumnModel;
import lt.dao.DaoCliente;
import lt.dao.DaoCuota;
import lt.dao.DaoTipoPlan;
import lt.dao.DaoVehiculo;
import lt.interfaces.InterfaceCliente;
import lt.models.Cliente;
import lt.models.Cuota;
import lt.models.TipoPlan;
import lt.models.Vehiculo;
import lt.tablas.ModeloTablaVehiculosCliente;
import lt.util.ConnectionHelper;
import lt.util.Utilidad;


/**
 *
 * @author brother
 */
public class PolizaView extends javax.swing.JDialog implements InterfaceCliente{

    private TipoPlan tipoPlan;
    private String accion;
    private DaoTipoPlan dao;
    private double montoCuotas;
    private Vehiculo vehiculo;
    private DaoVehiculo daoVehiculo;
    private Cuota cuota;
    private List<Cuota> cuotas;
     private ModeloTablaVehiculosCliente mtVehiculos;

    private DaoCuota daoCuotas;
    private DaoCliente daocliente;
    private Cliente cliente;
    private Integer codigo;
    private List<Vehiculo> vehiculosList;
    private LocalDate fechaAlta;

    /**
     * Creates new form RegistroPoliza
     */
    public PolizaView() {
        super();
        initComponents();
        setLocationRelativeTo(this);
        estadoInicial(true);
      
       
        formateoTabla();
     
      
       

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        body = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        datePicker1 = new com.github.lgooddatepicker.components.DatePicker();
        cbPlan = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txCostoPlan = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txCantidadDeCuotas = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txMontoCuota = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        mtVehiculos = new ModeloTablaVehiculosCliente();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txCobertura = new javax.swing.JTextArea();
        lblContratoActivo = new javax.swing.JLabel();
        lblFechaInicio = new javax.swing.JLabel();
        lblFechaVencimiento = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        head = new javax.swing.JPanel();
        btnBuscar = new javax.swing.JButton();
        lblCliente = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Asignación y Consulta de Pólizas");
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setModal(true);
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));

        jPanel6.setBackground(new java.awt.Color(237, 244, 246));

        body.setBackground(new java.awt.Color(237, 244, 246));

        jPanel3.setLayout(new java.awt.GridLayout(2, 3, 6, 6));

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lt/images/guardar35.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setBackground(new java.awt.Color(45, 118, 232));
        btnGuardar.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/lt/images/guardardisa.png"))); // NOI18N
        btnGuardar.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGuardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel3.add(btnGuardar);

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lt/images/cancelar35.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setBackground(new java.awt.Color(45, 118, 232));
        btnCancelar.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/lt/images/cancelardisa.png"))); // NOI18N
        btnCancelar.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel3.add(btnCancelar);

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lt/images/nuevo35.png"))); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.setBackground(new java.awt.Color(45, 118, 232));
        btnNuevo.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/lt/images/nuevodisa.png"))); // NOI18N
        btnNuevo.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnNuevo.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jPanel3.add(btnNuevo);

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lt/images/salir35.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setBackground(new java.awt.Color(45, 118, 232));
        btnSalir.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/lt/images/salirdisa.png"))); // NOI18N
        btnSalir.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel3.add(btnSalir);

        datePicker1.setBackground(new java.awt.Color(45, 118, 232));
        datePicker1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        cbPlan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar","Básico", "Medio", "Plus" }));
        cbPlan.setBackground(new java.awt.Color(237, 244, 246));
        cbPlan.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        cbPlan.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbPlanItemStateChanged(evt);
            }
        });
        cbPlan.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cbPlanFocusLost(evt);
            }
        });
        cbPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPlanActionPerformed(evt);
            }
        });

        jLabel3.setText("Costo de Plan:");
        jLabel3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        txCostoPlan.setDisabledTextColor(new java.awt.Color(25, 25, 25));
        txCostoPlan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txCostoPlanKeyPressed(evt);
            }
        });

        jLabel4.setText("Nº de Cuotas:");
        jLabel4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        txCantidadDeCuotas.setDisabledTextColor(new java.awt.Color(25, 25, 25));
        txCantidadDeCuotas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txCantidadDeCuotasFocusLost(evt);
            }
        });
        txCantidadDeCuotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txCantidadDeCuotasActionPerformed(evt);
            }
        });

        jLabel5.setText("Monto de Cuota:");
        jLabel5.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        txMontoCuota.setDisabledTextColor(new java.awt.Color(25, 25, 25));
        txMontoCuota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txMontoCuotaActionPerformed(evt);
            }
        });

        jScrollPane2.setMaximumSize(new java.awt.Dimension(458, 203));
        jScrollPane2.getViewport().setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(458, 203));
        jScrollPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane2MouseClicked(evt);
            }
        });

        jTable1.setModel(mtVehiculos);
        jTable1.setRowHeight(30);

        jTable1.setSelectionBackground(new java.awt.Color(92, 132, 228));

        jTable1.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jLabel2.setText("Plan:");
        jLabel2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cobertura del Plan:"));

        txCobertura.setColumns(20);
        txCobertura.setRows(5);
        txCobertura.setDisabledTextColor(new java.awt.Color(25, 25, 25));
        jScrollPane1.setViewportView(txCobertura);

        lblContratoActivo.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        lblFechaInicio.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        lblFechaVencimiento.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        lblEstado.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        jLabel7.setText("Fecha:");
        jLabel7.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        javax.swing.GroupLayout bodyLayout = new javax.swing.GroupLayout(body);
        body.setLayout(bodyLayout);
        bodyLayout.setHorizontalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(bodyLayout.createSequentialGroup()
                            .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cbPlan, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txCantidadDeCuotas, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txMontoCuota, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                                    .addComponent(txCostoPlan))))
                        .addComponent(jLabel7)
                        .addComponent(datePicker1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bodyLayout.createSequentialGroup()
                        .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFechaInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblFechaVencimiento, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE))
                        .addGap(65, 65, 65)
                        .addComponent(lblContratoActivo))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
            .addGroup(bodyLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        bodyLayout.setVerticalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyLayout.createSequentialGroup()
                .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bodyLayout.createSequentialGroup()
                        .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblContratoActivo, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(bodyLayout.createSequentialGroup()
                                .addComponent(lblEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblFechaVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12))
                    .addGroup(bodyLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(datePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bodyLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(bodyLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbPlan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txCostoPlan, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txCantidadDeCuotas, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txMontoCuota, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        head.setBackground(new java.awt.Color(45, 118, 232));

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lt/images/userNew.png"))); // NOI18N
        btnBuscar.setText("Agregar");
        btnBuscar.setBackground(new java.awt.Color(252, 253, 253));
        btnBuscar.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(45, 118, 232));
        btnBuscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBuscar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        lblCliente.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblCliente.setForeground(new java.awt.Color(255, 255, 255));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lt/images/icons8-Vehicle Insurance Filled.png"))); // NOI18N

        jLabel1.setText("N° de Póliza:");
        jLabel1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));

        lblCodigo.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lblCodigo.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout headLayout = new javax.swing.GroupLayout(head);
        head.setLayout(headLayout);
        headLayout.setHorizontalGroup(
            headLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(headLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCodigo))
                    .addGroup(headLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCliente)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );
        headLayout.setVerticalGroup(
            headLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headLayout.createSequentialGroup()
                .addGroup(headLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headLayout.createSequentialGroup()
                        .addGroup(headLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(headLayout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(lblCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(headLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(lblCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(head, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(body, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(head, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(body, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (validar()) {
        guardar();    
        }

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        nuevo();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void txCostoPlanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txCostoPlanKeyPressed
        Utilidad.moverConEnter(evt, txCantidadDeCuotas);
    }//GEN-LAST:event_txCostoPlanKeyPressed

    private void txMontoCuotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txMontoCuotaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txMontoCuotaActionPerformed

    private void txCantidadDeCuotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txCantidadDeCuotasActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_txCantidadDeCuotasActionPerformed

    private void txCantidadDeCuotasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txCantidadDeCuotasFocusLost
        // TODO add your handling code here:
        calcularCuota(txCostoPlan.getText(), txCantidadDeCuotas.getText());
    }//GEN-LAST:event_txCantidadDeCuotasFocusLost

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        buscadorClienteVehiculo busCliente = new buscadorClienteVehiculo();
        busCliente.setInterfaceCliente(this);

        buscadorClienteVehiculo.btnSeleccionar.setEnabled(true);

        busCliente.setVisible(true);
        btnCancelar.setEnabled(true);
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        cancelar();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void cbPlanFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbPlanFocusLost
        // TODO add your handling code here:
      recuperarPlan();
    }//GEN-LAST:event_cbPlanFocusLost

    private void cbPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPlanActionPerformed
        // TODO add your handling code here:     
    }//GEN-LAST:event_cbPlanActionPerformed

    private void cbPlanItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbPlanItemStateChanged
        try {
            mostrarPlanDescripcion();
        } catch (IOException ex) {
            Logger.getLogger(PolizaView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cbPlanItemStateChanged

    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_UP || evt.getKeyCode() == KeyEvent.VK_DOWN) {
            vaciarCampos();
            seleccionarVehiculo(jTable1.getSelectedRow());
        }
    }//GEN-LAST:event_jTable1KeyReleased

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        vaciarCampos();
        seleccionarVehiculo(jTable1.getSelectedRow());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jScrollPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        ConnectionHelper.setUp();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PolizaView dialog = new PolizaView();
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel body;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cbPlan;
    private com.github.lgooddatepicker.components.DatePicker datePicker1;
    private javax.swing.JPanel head;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblContratoActivo;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblFechaInicio;
    private javax.swing.JLabel lblFechaVencimiento;
    private javax.swing.JTextField txCantidadDeCuotas;
    private javax.swing.JTextArea txCobertura;
    private javax.swing.JTextField txCostoPlan;
    private javax.swing.JTextField txMontoCuota;
    // End of variables declaration//GEN-END:variables

    //BEGIN OF METHODS DECLARATIONS
    //Save in two tables --
    private void guardar() {
        if (accion.equals("NUEVO")) {
            tipoPlan = new TipoPlan();
             

        }
        tipoPlan.setMontoPoliza(Utilidad.formatoValorNumeroStringADouble(txCostoPlan.getText()));
        tipoPlan.setCantidadCuotas(Utilidad.formatoValorNumeroStringAInteger(txCantidadDeCuotas.getText()));
        tipoPlan.setMontoCouta(Utilidad.formatoValorNumeroStringADouble(txMontoCuota.getText()));
        tipoPlan.setNombrePlan(cbPlan.getSelectedItem().toString());
        tipoPlan.setFechaRegistro(datePicker1.getDate());
        tipoPlan.setEstadoActivo(true);
        daocliente = new DaoCliente();
        cliente = daocliente.recuperarPorId(vehiculo.getCliente().getCodigo());
        tipoPlan.setCliente(cliente);
        tipoPlan.setVehiculo(vehiculo);
        generarCoutas(Utilidad.formatoValorNumeroStringAInteger(txCantidadDeCuotas.getText()));
        try {
            dao = new DaoTipoPlan();
            dao.insertar(tipoPlan);
            dao.commit();
            estadoInicial(true);
            vaciarCampos();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Se ha producido un error en la carga de datos" + e);
            dao.rollback();
        }

    }

    //metodo que guarda en cuotas los detalles de la misma
    private void generarCoutas(int cuotas) {
        daocliente = new DaoCliente();
        cliente = daocliente.recuperarPorId(vehiculo.getCliente().getCodigo());
        for (int i = 0; i < cuotas; i++) {
            cuota = new Cuota();

            //calculo de fecha
            fechaAlta = datePicker1.getDate();
            cuota.setCliente(cliente);
            cuota.setTipoPlan(tipoPlan);
            cuota.setEstadoCuotas(false);
            cuota.setMontoCuota(montoCuotas);
            cuota.setSaldoCuota(montoCuotas);
            cuota.setCantidadCuota(Utilidad.formatoValorNumeroStringAInteger(txCantidadDeCuotas.getText()));
            cuota.setNumeroCuota(i + 1);
            cuota.setFechaVencimiento(fechaAlta.plus(i + 1, ChronoUnit.MONTHS));
            tipoPlan.addCuota(cuota);
        }
    }

    private void nuevo() {
        accion = "NUEVO";
     
        vaciarCampos();
        setearIdNuevo();
        estadoNuevo();
      
        
     
        

    }

    private void cancelar() {
        vaciarCampos();
        estadoInicial(true);
        lblCliente.setText("");
        List<Vehiculo> lista = new ArrayList();
        mtVehiculos.setLista(lista);
        jTable1.setModel(mtVehiculos);

    }

    private void vaciarCampos() {

        lblCodigo.setText("");
        txCostoPlan.setText("");
        txCantidadDeCuotas.setText("");
        txMontoCuota.setText("");
        txCobertura.setText("");
     

    }

    private void estadoInicial(Boolean estado) {
        //textFields

        txCostoPlan.setEnabled(!estado);
        txCantidadDeCuotas.setEnabled(!estado);
        txMontoCuota.setEnabled(!estado);
        txCobertura.setEnabled(!estado);
        cbPlan.setEnabled(!estado);
        datePicker1.setEnabled(!estado);
        //botones
        btnNuevo.setEnabled(!estado);
        btnBuscar.setEnabled(estado);

        btnGuardar.setEnabled(!estado);
        btnCancelar.setEnabled(!estado);
        //labels
        lblContratoActivo.setText("");
        lblEstado.setText("");
        lblFechaInicio.setText("");
        lblFechaVencimiento.setText("");
        

        
        btnNuevo.requestFocus();
        if (estado) {
            datePicker1.setText("");
        }
        if (!estado) {
            LocalDate hoy = LocalDate.now();
            datePicker1.setDate(hoy);
               estilosFecha();
        }
     

    }

    private void modificar() {
        accion = "MODIFICAR";
        estadoInicial(false);
        cbPlan.setEnabled(true);
        cbPlan.requestFocus();
        txCostoPlan.setEnabled(true);
       
        txCantidadDeCuotas.setEnabled(true);

    }

    private void calcularCuota(String montoTotal, String cantidadCuotas) {
        montoCuotas = Utilidad.formatoValorNumeroStringADouble(montoTotal) / Utilidad.formatoValorNumeroStringAInteger(cantidadCuotas);
        txMontoCuota.setText(Utilidad.formatoValorNumeroDoubleAString(montoCuotas));
        txMontoCuota.setEnabled(false);
    }

    //metodo que busca si existe vehiculo asociado a un plan
    private TipoPlan buscarPlan() {
        dao = new DaoTipoPlan();
        tipoPlan = dao.recuperarPorChapa(vehiculo);
        return tipoPlan;
    }


    private void recuperarPlan() {

        if (cbPlan.getSelectedItem().toString().equals("Seleccionar")) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar el tipo de plan");
            cbPlan.requestFocus();
        }
    }

    private void setearIdNuevo() {
        dao = new DaoTipoPlan();
        Integer id = dao.recuperarUltimoID();
        lblCodigo.setText(id +1+ "");
    }

    private void mostrarPlanDescripcion() throws IOException {
        int seleccionarPlan = cbPlan.getSelectedIndex();
        switch (seleccionarPlan) {
            case 1: {
                txCobertura.setText("");
                FileReader reader = null;
                try {
                    reader = new FileReader("txt/opcion1.txt");
                    BufferedReader br = new BufferedReader(reader);
                    String line = br.readLine();
                    while (line != null) {
                        txCobertura.append(line + "\n");
                        line = br.readLine();
                    }
                        } catch (FileNotFoundException ex) {
                    Logger.getLogger(PolizaView.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            break;
            case 2: {
                txCobertura.setText("");
                FileReader reader = null;
                String path;
                try {                  
                    reader = new FileReader("txt/opcion2.txt");
                    BufferedReader br = new BufferedReader(reader);
                    String line = br.readLine();
                    while (line != null) {
                        txCobertura.append(line + "\n");
                        line = br.readLine();
                    }
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(PolizaView.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            break;
            case 3: {
                txCobertura.setText("");
                FileReader reader = null;
                try {
                    reader = new FileReader("txt/opcion3.txt");
                    BufferedReader br = new BufferedReader(reader);
                    String line = br.readLine();
                    while (line != null) {
                        txCobertura.append(line + "\n");
                        line = br.readLine();
                    }
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(PolizaView.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            break;
        }
    }

    @Override
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
      codigo = cliente.getCodigo();
      lblCliente.setText("Cliente: "+cliente.getNombre()+" "+cliente.getApellido());
       setearTablaVehiculos();

     
       formateoTabla();
    }
    
    public void setearTablaVehiculos(){
        daoVehiculo = new DaoVehiculo();
        vehiculosList = daoVehiculo.recuperarVehiculoPorIdCliente(cliente);
        mtVehiculos.setLista(vehiculosList);
        jTable1.setModel(mtVehiculos);
    }
        private void seleccionarVehiculo(int index) {
        if (index < 0) {
            return;
        }

        vehiculo = vehiculosList.get(index);
        tipoPlan = buscarPlan();
                if (tipoPlan == null) {
               
               
               estadoSinPoliza();
            } 
                else if(tipoPlan.getEstadoActivo().equals(false)){
                    estadoSinPoliza();
                }
                else{
               
            try {
                estadoInicial(true);
                infoContrato();
                lblCodigo.setText(tipoPlan.getCodigo() + "");
                txCostoPlan.setText(Utilidad.formatoValorNumeroDoubleAString(tipoPlan.getMontoPoliza()));
                txMontoCuota.setText(Utilidad.formatoValorNumeroDoubleAString(tipoPlan.getMontoCouta()));
                txCantidadDeCuotas.setText(Utilidad.formatoValorNumeroIntegerAString(tipoPlan.getCantidadCuotas()));
                mostrarPlanDescripcion();
                cbPlan.setSelectedItem(tipoPlan.getNombrePlan());
            } catch (IOException ex) {
                Logger.getLogger(PolizaView.class.getName()).log(Level.SEVERE, null, ex);
            }
            }
        
}

    private void estilosFecha() {

        datePicker1.getComponentDateTextField().setEnabled(false);
        datePicker1.setLocale(Locale.forLanguageTag("Es"));
        datePicker1.getComponentDateTextField().setDisabledTextColor(Color.BLACK);

    }    

    private void estadoSinPoliza() {
        //botones
        btnNuevo.setEnabled(true);
        btnCancelar.setEnabled(true);
        cbPlan.setSelectedIndex(0);
        lblContratoActivo.setText("No posee contrato activo");
        lblFechaInicio.setText("");
        lblFechaVencimiento.setText("");
        lblEstado.setText("");
    }

    private void estadoNuevo() {
        btnCancelar.setEnabled(true);
        btnGuardar.setEnabled(true);
        btnNuevo.setEnabled(false);
        estadoInicial(false);
    }

    private void infoContrato() {
     lblContratoActivo.setText("");
      int nroCuotas = tipoPlan.getCantidadCuotas();
      Locale es = new Locale("Es");
        DateTimeFormatter ff = DateTimeFormatter.ofPattern("dd/MM/yyyy", es);
        LocalDate fechaInicio = tipoPlan.getFechaRegistro();
        LocalDate fechaVencimiento = fechaInicio.plus(nroCuotas, ChronoUnit.MONTHS);
        lblFechaInicio.setText("Inicio de Contrato: "+fechaInicio.format(ff));
        lblFechaVencimiento.setText("Fin de Contrato: "+fechaVencimiento.format(ff));
        lblEstado.setText("Estado: Activo");
       
    }
    
     private void formateoTabla() {
        TableColumnModel columnModel = jTable1.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(140);
        columnModel.getColumn(1).setPreferredWidth(115);
        columnModel.getColumn(2).setPreferredWidth(120);
        columnModel.getColumn(3).setPreferredWidth(100);
        jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        jTable1.doLayout();

        //alineamiento de celdas
        DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
        tcr.setHorizontalAlignment(SwingConstants.RIGHT);

       }
     private boolean validar(){
         boolean validar = false;
         if (txCostoPlan.getText().isEmpty()) {
             JOptionPane.showMessageDialog(null, "No ha ingresado el monto para la póliza, favor verifique");
             txCostoPlan.requestFocus();
         }
          else if (txCantidadDeCuotas.getText().isEmpty()) {
             JOptionPane.showMessageDialog(null, "No ha ingresado la cantidad de cuotas para la póliza, favor verifique");
             txCantidadDeCuotas.requestFocus();
         }else if(cbPlan.getSelectedIndex()==0){
             JOptionPane.showMessageDialog(null, "No ha seleccionado el tipo de plan, favor verifique");
             cbPlan.requestFocus();
         }
          else{
              validar =true;
          }
         
         return validar;
     }
}