/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lt.views;

import java.awt.BorderLayout;
import java.awt.Color;

import java.util.List;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import lt.dao.DaoConfig;
import lt.dao.DaoInicializacion;
import lt.models.Config;
import lt.reportes.entities.informePlan;
import lt.reportes.view.InfomeDePlan;
import lt.reportes.view.InformeCobranzasView;
import lt.reportes.view.InformeCobrosCliente;
import lt.reportes.view.ListaClienteView;
import lt.reportes.view.ListaVehiculosView;
import lt.util.ConnectionHelper;
import lt.util.PanelFondo;

/**
 *
 * @author brother
 */
public class Principal extends javax.swing.JFrame {

    private static DaoConfig daoConfig;
    private static Config configuracion;

    private DaoInicializacion daoInicializar;
    private List<String> tablas;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        setLocationRelativeTo(this);
        revisarConfiguracion();
        setExtendedState(MAXIMIZED_BOTH);
        //btnCobranza.setUI(new BEButtonUI().setNormalColor(BEButtonUI.NormalColor.lightBlue));

       
        checkColors();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        //jPanel2 = new PanelFondo();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnCobranza = new javax.swing.JButton();
        btnPoliza = new javax.swing.JButton();
        btnCliente = new javax.swing.JButton();
        btnVehiculo = new javax.swing.JButton();
        btnSalir1 = new javax.swing.JButton();
        lblVersion = new javax.swing.JLabel();
        lblAuthor = new javax.swing.JLabel();
        lblOrga = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnRegistroCobranza = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnCliente = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Gestión  de Aseguradora de Vehículos");
        setBackground(new java.awt.Color(197, 216, 236));
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        setSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lt/images/gear.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1920, 1200);

        jPanel3.setBackground(new java.awt.Color(253, 252, 252));

        //this.add(jPanel1, BorderLayout.CENTER);
        //jPanel1.repaint();
        jPanel2.setBackground(new java.awt.Color(175, 180, 187));
        jPanel2.setMaximumSize(new java.awt.Dimension(1920, 32767));
        jPanel2.setPreferredSize(new java.awt.Dimension(1920, 321));

        jPanel1.setBackground(new java.awt.Color(175, 180, 187));
        jPanel1.setLayout(new java.awt.GridLayout(1, 4, 12, 0));

        btnCobranza.setBackground(new java.awt.Color(255, 255, 255));
        btnCobranza.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnCobranza.setForeground(new java.awt.Color(45, 118, 232));
        btnCobranza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lt/images/cobros_1.png"))); // NOI18N
        btnCobranza.setText("Cobranza");
        btnCobranza.setToolTipText("Cobranzas");
        btnCobranza.setBorderPainted(false);
        btnCobranza.setFocusPainted(false);
        btnCobranza.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCobranza.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCobranza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCobranzaActionPerformed(evt);
            }
        });
        jPanel1.add(btnCobranza);

        btnPoliza.setBackground(new java.awt.Color(255, 255, 255));
        btnPoliza.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnPoliza.setForeground(new java.awt.Color(45, 118, 232));
        btnPoliza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lt/images/poliza_1.png"))); // NOI18N
        btnPoliza.setText("Póliza");
        btnPoliza.setToolTipText("Póliza");
        btnPoliza.setBorderPainted(false);
        btnPoliza.setFocusPainted(false);
        btnPoliza.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPoliza.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPoliza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPolizaActionPerformed(evt);
            }
        });
        jPanel1.add(btnPoliza);

        btnCliente.setBackground(new java.awt.Color(255, 255, 255));
        btnCliente.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnCliente.setForeground(new java.awt.Color(45, 118, 232));
        btnCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lt/images/cliente_1.png"))); // NOI18N
        btnCliente.setText("Cliente");
        btnCliente.setToolTipText("Cliente");
        btnCliente.setBorderPainted(false);
        btnCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCliente.setFocusPainted(false);
        btnCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCliente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteActionPerformed(evt);
            }
        });
        jPanel1.add(btnCliente);

        btnVehiculo.setBackground(new java.awt.Color(255, 255, 255));
        btnVehiculo.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnVehiculo.setForeground(new java.awt.Color(45, 118, 232));
        btnVehiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lt/images/coche_1.png"))); // NOI18N
        btnVehiculo.setText("Vehículo");
        btnVehiculo.setToolTipText("Vehículo");
        btnVehiculo.setActionCommand("");
        btnVehiculo.setBorderPainted(false);
        btnVehiculo.setFocusPainted(false);
        btnVehiculo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVehiculo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVehiculoActionPerformed(evt);
            }
        });
        jPanel1.add(btnVehiculo);

        btnSalir1.setBackground(new java.awt.Color(255, 255, 255));
        btnSalir1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnSalir1.setForeground(new java.awt.Color(45, 118, 232));
        btnSalir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lt/images/salir_2.png"))); // NOI18N
        btnSalir1.setText("Salir");
        btnSalir1.setToolTipText("Salir");
        btnSalir1.setBorderPainted(false);
        btnSalir1.setFocusPainted(false);
        btnSalir1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalir1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalir1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir1);

        lblVersion.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        lblVersion.setForeground(new java.awt.Color(255, 255, 255));
        lblVersion.setText("Versión 1.9");

        lblAuthor.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        lblAuthor.setForeground(new java.awt.Color(255, 255, 255));
        lblAuthor.setText("Luis Torres");

        lblOrga.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblOrga.setForeground(new java.awt.Color(255, 255, 255));

        lblAddress.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblAddress.setForeground(new java.awt.Color(255, 255, 255));

        lblTelefono.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblTelefono.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1003, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 647, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(lblTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(81, 81, 81))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblOrga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblVersion)
                            .addComponent(lblAuthor))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(lblOrga, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(44, 44, 44)
                .addComponent(lblVersion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 153));
        jLabel3.setText("Sistema de Gestión  de Aseguradora de Vehículos");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(39, 39, 39))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 609, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(87, 87, 87))
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 1920, 1050);

        jMenuBar1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jMenuBar1.setPreferredSize(new java.awt.Dimension(258, 30));

        jMenu1.setText("Procesos");
        jMenu1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        mnRegistroCobranza.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        mnRegistroCobranza.setText("Registro de Cobranza");
        mnRegistroCobranza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnRegistroCobranzaActionPerformed(evt);
            }
        });
        jMenu1.add(mnRegistroCobranza);

        jMenuItem2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jMenuItem2.setText("Póliza");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Tablas");
        jMenu2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        mnCliente.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        mnCliente.setText("Cliente");
        mnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnClienteActionPerformed(evt);
            }
        });
        jMenu2.add(mnCliente);

        jMenuItem1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jMenuItem1.setText("Vehículo");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Informes");
        jMenu3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        jMenuItem3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jMenuItem3.setText("Listado de Cliente");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuItem4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jMenuItem4.setText("Listado de Vehículos");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuItem6.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jMenuItem6.setText("Informe de Cobranzas");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem6);

        jMenuItem5.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jMenuItem5.setText("Informe de Planes");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuItem9.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jMenuItem9.setText("Cobros por Cliente");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem9);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Utilidades");
        jMenu4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        jMenuItem7.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jMenuItem7.setText("Configuraciones");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem7);

        jMenuItem8.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jMenuItem8.setText("Inicialización de Datos");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem8);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteActionPerformed
        CustomerView customer = new CustomerView(this, rootPaneCheckingEnabled);
        customer.setVisible(true);

    }//GEN-LAST:event_btnClienteActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        CarView car = new CarView();
        car.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnCobranzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCobranzaActionPerformed
        CobrosView cobros = new CobrosView();
        cobros.setVisible(true);
    }//GEN-LAST:event_btnCobranzaActionPerformed

    private void btnVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVehiculoActionPerformed
        CarView car = new CarView();
        car.setVisible(true);
    }//GEN-LAST:event_btnVehiculoActionPerformed

    private void btnPolizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPolizaActionPerformed
        PolizaView poliza = new PolizaView();
        poliza.setVisible(true);
    }//GEN-LAST:event_btnPolizaActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        resetDataBase();
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void btnSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalir1ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        ConfiguracionInicial ini = new ConfiguracionInicial();
        ini.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void mnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnClienteActionPerformed
        CustomerView customer = new CustomerView(this, rootPaneCheckingEnabled);
        customer.setVisible(true);

    }//GEN-LAST:event_mnClienteActionPerformed

    private void mnRegistroCobranzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnRegistroCobranzaActionPerformed
        CobrosView cobros = new CobrosView();
        cobros.setVisible(true);
    }//GEN-LAST:event_mnRegistroCobranzaActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        ListaClienteView lista = new ListaClienteView();
        lista.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        ListaVehiculosView vehiculos = new ListaVehiculosView();
        vehiculos.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        InformeCobranzasView info = new InformeCobranzasView();
        info.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        PolizaView poli = new PolizaView();
        poli.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
            InfomeDePlan info = new InfomeDePlan();
            info.setVisible(true);
        
        
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        InformeCobrosCliente cli = new InformeCobrosCliente(this, rootPaneCheckingEnabled);
        cli.setVisible(true);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        ConnectionHelper.setUp();
      

        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCliente;
    private javax.swing.JButton btnCobranza;
    private javax.swing.JButton btnPoliza;
    private javax.swing.JButton btnSalir1;
    private javax.swing.JButton btnVehiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    public static javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public static javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblAuthor;
    public static javax.swing.JLabel lblOrga;
    public static javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblVersion;
    private javax.swing.JMenuItem mnCliente;
    private javax.swing.JMenuItem mnRegistroCobranza;
    // End of variables declaration//GEN-END:variables

    // Metodo que reinicia todos los datos de la base de datos
    private void resetDataBase() {
        int opcion = JOptionPane.showConfirmDialog(this, "Cuidado, esta operacion elimina los datos permanentemente.\n"
                + " Desea continuar?", "Aviso", 1, JOptionPane.YES_NO_OPTION);
        if (opcion == JOptionPane.OK_OPTION) {

            daoInicializar = new DaoInicializacion();
            tablas = daoInicializar.recuperarNombreTablas();
            String target1 = "departamentos";
            String target2 = "distritos";
            for (int i = 0; i < tablas.size(); i++) {
                daoInicializar = new DaoInicializacion();
                if (!target1.equals(tablas.get(i)) && !target2.equals(tablas.get(i))) {
                    daoInicializar.inicializarTablas(tablas.get(i));
                    
                }

            }
           

          
            JOptionPane.showMessageDialog(this, "La base de datos ha sido reiniciada con exito");
        }
    }

    public static void revisarConfiguracion() {
        daoConfig = new DaoConfig();
        configuracion = daoConfig.recuperarPorId(1);
        if (configuracion == null) {
            jMenuItem7.setEnabled(true);
            lblOrga.setText("");
            lblAddress.setText("");
            lblTelefono.setText("");
            //jMenuItem7.setEnabled(false);
        } else {
            jMenuItem7.setEnabled(false);
            lblOrga.setText(configuracion.getOrganizacionNombre());
            lblAddress.setText(configuracion.getOrganizacionDomicilio());
            lblTelefono.setText(configuracion.getOrganizacionTelefono());
        }
    }

    private void checkColors() {
        if (btnCliente.isEnabled()) {
            btnCliente.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    btnCliente.setBackground(new java.awt.Color(255, 130, 79));
                    btnCliente.setForeground(Color.WHITE);
                }

                public void mouseExited(java.awt.event.MouseEvent evt) {
                    btnCliente.setBackground(new java.awt.Color(255, 255, 255));
                    btnCliente.setForeground(new java.awt.Color(25, 118, 232));
                }
            });
        }
        if (btnCobranza.isEnabled()) {
            btnCobranza.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    btnCobranza.setBackground(new java.awt.Color(255, 130, 79));
                    btnCobranza.setForeground(Color.WHITE);
                }

                public void mouseExited(java.awt.event.MouseEvent evt) {
                    btnCobranza.setBackground(new java.awt.Color(255, 255, 255));
                    btnCobranza.setForeground(new java.awt.Color(25, 118, 232));
                }
            });
        }
        if (btnPoliza.isEnabled()) {
            btnPoliza.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    btnPoliza.setBackground(new java.awt.Color(255, 130, 79));
                    btnPoliza.setForeground(Color.WHITE);
                }

                public void mouseExited(java.awt.event.MouseEvent evt) {
                    btnPoliza.setBackground(new java.awt.Color(255, 255, 255));
                    btnPoliza.setForeground(new java.awt.Color(25, 118, 232));
                }
            });
        }
        if (btnSalir1.isEnabled()) {
            btnSalir1.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    btnSalir1.setBackground(new java.awt.Color(255, 130, 79));
                    btnSalir1.setForeground(Color.WHITE);
                }

                public void mouseExited(java.awt.event.MouseEvent evt) {
                    btnSalir1.setBackground(new java.awt.Color(255, 255, 255));
                    btnSalir1.setForeground(new java.awt.Color(25, 118, 232));
                }
            });
        }
        if (btnVehiculo.isEnabled()) {
            btnVehiculo.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    btnVehiculo.setBackground(new java.awt.Color(255, 130, 79));
                    btnVehiculo.setForeground(Color.WHITE);
                }

                public void mouseExited(java.awt.event.MouseEvent evt) {
                    btnVehiculo.setBackground(new java.awt.Color(255, 255, 255));
                    btnVehiculo.setForeground(new java.awt.Color(25, 118, 232));
                }
            });
        }
    }

}
